#!/usr/bin/env bash
# wg0 Connector — macOS
#
# Enrolls a macOS node with the Brain and maintains WireGuard connectivity.
# Automatically installs Homebrew dependencies (wireguard-tools, jq) if missing.
# Works on Apple Silicon (arm64) and Intel (x86_64). Requires macOS 11+.
#
# Usage:
#   sudo ./connector-macos.sh enroll <TOKEN> <BRAIN_URL> [NODE_NAME] [ROLE]
#   sudo ./connector-macos.sh unenroll <BRAIN_URL>
#
# Examples:
#   # Host node (macOS machine on your LAN — used for native LAN mode)
#   sudo ./connector-macos.sh enroll eyJhbG... https://brain.example.com $(hostname) host
#
#   # Client node (remote device that connects through the network)
#   sudo ./connector-macos.sh enroll eyJhbG... https://brain.example.com my-macbook client
#
#   # Remove this node from the Brain and wipe all local WireGuard config
#   sudo ./connector-macos.sh unenroll https://brain.example.com
#
# Idempotent enroll — safe to re-run.

set -euo pipefail

# ── Constants ─────────────────────────────────────────────────────────────────
WG_IFACE="wg0"
WG_CONF="/etc/wireguard/${WG_IFACE}.conf"
INSTALLATION_ID_FILE="/etc/wireguard/installation_id"
DEVICE_ID_FILE="/etc/wireguard/device_id"
KEY_DIR="/etc/wireguard/wg0"
PRIV_KEY_FILE="${KEY_DIR}/private.key"
PUB_KEY_FILE="${KEY_DIR}/public.key"
NODE_ID_FILE="${KEY_DIR}/node_id"
DEVICE_SECRET_FILE="${KEY_DIR}/device_secret"
CONFIG_VERSION_FILE="${KEY_DIR}/config_version"
HEARTBEAT_INTERVAL=30
HEARTBEAT_SCRIPT="/usr/local/bin/wg0-heartbeat"
POSTUP_SCRIPT="/usr/local/bin/wg0-postup"
PREDOWN_SCRIPT="/usr/local/bin/wg0-predown"
LAUNCHDAEMON_PLIST="/Library/LaunchDaemons/io.wg0.heartbeat.plist"
WG_WATCHDOG_PLIST="/Library/LaunchDaemons/io.wg0.wireguard.plist"

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "[wg0 $(date -u +%H:%M:%SZ)] $*"; }
die()  { log "ERROR: $*" >&2; exit 1; }
warn() { log "WARNING: $*" >&2; }

get_or_create_installation_id() {
    local iid=""
    if [[ -f "$INSTALLATION_ID_FILE" ]]; then
        iid="$(cat "$INSTALLATION_ID_FILE" 2>/dev/null || true)"
    fi
    if [[ -z "$iid" ]]; then
        iid="$(uuidgen 2>/dev/null || true)"
        [[ -n "$iid" ]] || die "Unable to generate installation_id"
        printf '%s' "$iid" > "$INSTALLATION_ID_FILE"
        chmod 600 "$INSTALLATION_ID_FILE"
    fi
    printf '%s' "$iid"
}

# ── Must run as root ──────────────────────────────────────────────────────────
[[ "$EUID" -eq 0 ]] || die "This script must be run with sudo."

# ── Architecture detection + Homebrew path ────────────────────────────────────
ARCH=$(uname -m)
if [[ "$ARCH" == "arm64" ]]; then
    BREW_PREFIX="/opt/homebrew"
else
    BREW_PREFIX="/usr/local"
fi
BREW="${BREW_PREFIX}/bin/brew"

# ── Heartbeat template writer ─────────────────────────────────────────────────
# Used by both `enroll` and `update`. Reads global vars: HEARTBEAT_SCRIPT,
# BRAIN_URL, NODE_ID_FILE, WG_IFACE, BREW_PREFIX. Writes a fresh script that:
#   - Resolves the real utun interface (macOS userspace WireGuard quirk)
#   - Reports TX/RX bytes via heartbeat
#   - Applies peer map via `wg set`
#   - Adds matching system routes (delete-then-add for idempotency across
#     interface renumbering when wireguard-go restarts)
write_heartbeat_script() {
    cat > "$HEARTBEAT_SCRIPT" <<HBSCRIPT
#!/usr/bin/env bash
# Auto-generated by wg0 connector (macOS). Do not edit manually.
export PATH="${BREW_PREFIX}/bin:${BREW_PREFIX}/sbin:\$PATH"
NODE_ID="\$(cat ${NODE_ID_FILE})"
ROUTE_ALL_STATE="${KEY_DIR}/route_all_state"
ROUTE_ALL_DNS_STATE="${KEY_DIR}/route_all_dns_state"
SAME_LAN_STATE="${KEY_DIR}/same_lan_state"
OVERLAY_IP_FILE="${KEY_DIR}/overlay_ip"
COLLECT_TELEMETRY_STATE="${KEY_DIR}/collect_device_telemetry"

find_bin() {
    local name="\$1"
    for path in \
        "${BREW_PREFIX}/bin/\${name}" \
        "${BREW_PREFIX}/sbin/\${name}" \
        "/usr/local/bin/\${name}" \
        "/usr/local/sbin/\${name}" \
        "/usr/bin/\${name}" \
        "/usr/sbin/\${name}"; do
        [[ -n "\$path" && -x "\$path" ]] && { printf '%s' "\$path"; return 0; }
    done
    printf '%s' "\$name"
}

WG_BIN=\$(find_bin wg)
WG_QUICK_BIN=\$(find_bin wg-quick)

resolve_wg_real() {
    local name up_name iface_list candidate
    name=\$(cat /var/run/wireguard/${WG_IFACE}.name 2>/dev/null | tr -d '[:space:]')
    if [[ -n "\$name" ]] && "\$WG_BIN" show "\$name" >/dev/null 2>&1; then
        printf '%s' "\$name"
        return 0
    fi
    if "\$WG_BIN" show "${WG_IFACE}" >/dev/null 2>&1; then
        printf '%s' "${WG_IFACE}"
        return 0
    fi
    up_name=\$(cat /var/run/wireguard/wg0-up.name 2>/dev/null | tr -d '[:space:]')
    iface_list=\$("\$WG_BIN" show interfaces 2>/dev/null || true)
    for candidate in \$iface_list; do
        [[ -n "\$up_name" && "\$candidate" == "\$up_name" ]] && continue
        printf '%s' "\$candidate"
        return 0
    done
    return 1
}

# macOS userspace WireGuard maps the logical name (wg0) to a utun device.
# Every wg/route call must use the real utun name, not the logical alias.
WG_REAL=\$(resolve_wg_real || true)
[[ -z "\$WG_REAL" ]] && WG_REAL="${WG_IFACE}"

# If wireguard-go is not running, skip — the watchdog will restart it.
"\$WG_BIN" show "\$WG_REAL" >/dev/null 2>&1 || exit 0

# Device protocol v2 secret (see docs/DEVICE_PROTOCOL.md). Empty string
# for nodes enrolled before v2 — the brain's grace-period path accepts
# the legacy "node_id is the credential" behavior for those rows.
DEVICE_SECRET=\$(cat "${DEVICE_SECRET_FILE}" 2>/dev/null || true)

PUBLIC_IP=\$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "")
ENDPOINT=""
[[ -n "\$PUBLIC_IP" ]] && ENDPOINT="\${PUBLIC_IP}:51820"

# Collect TX/RX bytes from WireGuard (wg show transfer: <pubkey> <rx> <tx>)
TRANSFER=\$("\$WG_BIN" show "\$WG_REAL" transfer 2>/dev/null)
TX_BYTES=\$(echo "\$TRANSFER" | awk '{sum += \$3} END {print sum+0}')
RX_BYTES=\$(echo "\$TRANSFER" | awk '{sum += \$2} END {print sum+0}')

# Per-peer observations from \`wg show <iface> dump\` — the brain merges
# these with the discover sidecar for the four-state presence model.
# Dump format: the first line is the interface (4 fields), subsequent
# lines are peers (8 fields: pubkey, psk, endpoint, allowed_ips,
# latest_handshake, rx, tx, keepalive). latest_handshake == 0 means
# "never," which we map to JSON null so the brain's Option<i64> is
# honest about missing data. jq -Rsc builds the JSON safely — no
# string concat, pubkeys are untrusted.
PEERS_JSON=\$("\$WG_BIN" show "\$WG_REAL" dump 2>/dev/null | tail -n +2 | awk -F'\\t' 'NF>=8 {
    printf "%s\\t%s\\t%s\\t%s\\n", \$1, \$5, \$6, \$7
}' | jq -Rsc '
    split("\\n") | map(select(length > 0) | split("\\t") | {
        public_key: .[0],
        last_handshake: (if .[1] == "0" then null else (.[1] | tonumber) end),
        rx_bytes: (.[2] | tonumber),
        tx_bytes: (.[3] | tonumber)
    })' 2>/dev/null)
[[ -z "\$PEERS_JSON" ]] && PEERS_JSON="[]"

# Build the POST body with jq so observed peer data is always valid JSON
# (avoids shell-quoting foot-guns when pubkeys contain \`/\` or \`+\`).
# Report whether route-all is currently active. Read from the state
# file the previous heartbeat cycle wrote. Used by the brain to
# suppress the public-IP-equality same-LAN heuristic (which gives a
# false positive when route-all egresses the client through the host).
ROUTE_ALL_PREV_STATE=\$(cat "${KEY_DIR}/route_all_state" 2>/dev/null || echo "off")
if [[ "\$ROUTE_ALL_PREV_STATE" == on* ]]; then
    ROUTE_ALL_ACTIVE=true
else
    ROUTE_ALL_ACTIVE=false
fi

current_capabilities_json() {
    # See connector.sh for the multi_membership_v1 rationale. macOS
    # connector inherits the same per-interface state-dir model
    # (/etc/wireguard/wgN) so advertising this capability is safe.
    jq -cn '[
        "same_lan_detection",
        "split_tunnel_macos",
        "byo_exit_macos",
        "assisted_relay_probe_peers_v1",
        "peer_observations",
        "device_telemetry_v1",
        "desired_state_convergence",
        "multi_membership_v1"
    ]'
}

is_ipv4_cidr() {
    local value="\${1:-}"
    [[ "\$value" =~ ^([0-9]{1,3}\\.){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$ ]]
}

first_valid_ipv4_cidr() {
    local raw="\${1:-}" route
    IFS=',' read -ra routes <<< "\$raw"
    for route in "\${routes[@]}"; do
        route=\$(echo "\$route" | xargs)
        [[ -z "\$route" ]] && continue
        if is_ipv4_cidr "\$route"; then
            printf '%s\n' "\$route"
            return 0
        fi
    done
    return 1
}

detect_host_lan_ip() {
    [[ "\$ROLE" == "host" ]] || { echo ""; return; }
    [[ -n "\$ADVERTISED_ROUTES_CSV" ]] || { echo ""; return; }

    local iface="" first_route="" probe_ip=""
    first_route=\$(first_valid_ipv4_cidr "\$ADVERTISED_ROUTES_CSV" || true)
    if [[ -n "\$first_route" ]]; then
        probe_ip=\$(echo "\$first_route" | cut -d/ -f1)
        iface=\$( { /usr/sbin/route -n get "\$probe_ip" 2>/dev/null || true; } | awk '/interface:/{print \$2; exit}')
    fi
    [[ -n "\$iface" ]] || iface=\$(/usr/sbin/route -n get default 2>/dev/null | awk '/interface:/{print \$2; exit}')
    [[ -n "\$iface" ]] || { echo ""; return; }

    /usr/sbin/ipconfig getifaddr "\$iface" 2>/dev/null \
        || /sbin/ifconfig "\$iface" 2>/dev/null | awk '/inet /{print \$2; exit}'
}

collect_battery_json() {
    local batt percent status charging=false
    batt=\$(pmset -g batt 2>/dev/null | tail -1)
    [[ -n "\$batt" ]] || { echo "null"; return; }
    percent=\$(echo "\$batt" | sed -n 's/.* \([0-9][0-9]*\)%;.*/\1/p')
    status=\$(echo "\$batt" | awk -F'; *' 'NF >= 2 { print \$2; exit }' | tr '[:upper:]' '[:lower:]')
    [[ -n "\$percent" || -n "\$status" ]] || { echo "null"; return; }
    [[ "\$status" == charging* || "\$status" == "charged" ]] && charging=true
    jq -cn \
        --argjson level_percent "\${percent:-null}" \
        --argjson charging "\$charging" \
        --arg status "\$status" \
        '{level_percent:\$level_percent, charging:\$charging, status:(\$status | select(length > 0)), health:null, temperature_c:null, voltage_mv:null}'
}

collect_cpu_json() {
    local logical_cpu total_cpu app_cpu
    logical_cpu=\$(sysctl -n hw.logicalcpu 2>/dev/null || echo 1)
    total_cpu=\$(ps -A -o %cpu= 2>/dev/null | awk -v cores="\$logical_cpu" '{sum += \$1} END { if (cores <= 0) cores = 1; v = sum / cores; if (v < 0) v = 0; if (v > 100) v = 100; printf "%.2f", v }')
    app_cpu=\$(ps -o %cpu= -p $$ 2>/dev/null | awk '{print \$1; exit}')
    [[ -n "\$total_cpu" || -n "\$app_cpu" ]] || { echo "null"; return; }
    jq -cn \
        --argjson system_usage_percent "\${total_cpu:-null}" \
        --argjson app_usage_percent "\${app_cpu:-null}" \
        --argjson sample_window_ms 30000 \
        '{system_usage_percent:\$system_usage_percent, app_usage_percent:\$app_usage_percent, sample_window_ms:\$sample_window_ms}'
}

collect_memory_json() {
    local total_bytes page_size free_pages speculative_pages inactive_pages available_bytes rss_kb low_memory
    total_bytes=\$(sysctl -n hw.memsize 2>/dev/null || echo "")
    page_size=\$(vm_stat 2>/dev/null | awk '/page size of/ {gsub("\\.", "", \$8); print \$8; exit}')
    free_pages=\$(vm_stat 2>/dev/null | awk '/Pages free/ {gsub("\\.", "", \$3); print \$3; exit}')
    speculative_pages=\$(vm_stat 2>/dev/null | awk '/Pages speculative/ {gsub("\\.", "", \$3); print \$3; exit}')
    inactive_pages=\$(vm_stat 2>/dev/null | awk '/Pages inactive/ {gsub("\\.", "", \$3); print \$3; exit}')
    [[ -n "\$total_bytes" && -n "\$page_size" ]] || { echo "null"; return; }
    available_bytes=\$(( (free_pages + speculative_pages + inactive_pages) * page_size ))
    rss_kb=\$(ps -o rss= -p $$ 2>/dev/null | awk '{print \$1; exit}')
    low_memory=\$(awk -v a="\$available_bytes" -v t="\$total_bytes" 'BEGIN { print (t > 0 && (a / t) < 0.10) ? "true" : "false" }')
    jq -cn \
        --argjson total_bytes "\$total_bytes" \
        --argjson available_bytes "\$available_bytes" \
        --argjson app_pss_bytes "\${rss_kb:-0}" \
        --argjson low_memory "\$low_memory" \
        '{total_bytes:\$total_bytes, available_bytes:\$available_bytes, app_pss_bytes:(\$app_pss_bytes * 1024), low_memory:\$low_memory}'
}

collect_device_telemetry_json() {
    [[ "\$(cat "\$COLLECT_TELEMETRY_STATE" 2>/dev/null || echo off)" == "on" ]] || { echo "null"; return; }
    local battery_json cpu_json memory_json
    battery_json=\$(collect_battery_json)
    cpu_json=\$(collect_cpu_json)
    memory_json=\$(collect_memory_json)
    if [[ "\$battery_json" == "null" && "\$cpu_json" == "null" && "\$memory_json" == "null" ]]; then
        echo "null"
        return
    fi
    jq -cn \
        --argjson battery "\$battery_json" \
        --argjson cpu "\$cpu_json" \
        --argjson memory "\$memory_json" \
        '{battery:\$battery, cpu:\$cpu, memory:\$memory}'
}

# BYO Exit kill-switch health probe. If a previous heartbeat's BYO
# state machine brought up wg0-up via wg-quick, we can read its
# current handshake timestamp via \`wg show\` and report it to the
# brain so the dashboard can surface upstream failures. macOS maps
# the logical name "wg0-up" to a utun device via
# /var/run/wireguard/wg0-up.name (same pattern as wg0). Non-hosts
# and hosts without a currently-installed upstream send null so
# the brain doesn't overwrite anything.
UPSTREAM_HEALTH_JSON="null"
if [[ -f "/var/run/wireguard/wg0-up.name" ]]; then
    WG_UP_REAL=\$(cat /var/run/wireguard/wg0-up.name 2>/dev/null | tr -d '[:space:]')
    if [[ -n "\$WG_UP_REAL" ]] && "\$WG_BIN" show "\$WG_UP_REAL" >/dev/null 2>&1; then
        # latest-handshakes output is "<pubkey>\\t<unix_seconds>"
        # per peer. 0 means "never handshook." Take the max across
        # all peers (there's usually one — the provider's endpoint).
        WG_UP_LAST_HS=\$("\$WG_BIN" show "\$WG_UP_REAL" latest-handshakes 2>/dev/null | awk '{ if (\$2 > 0) print \$2 }' | sort -nr | head -1)
        if [[ -n "\$WG_UP_LAST_HS" ]]; then
            UPSTREAM_HEALTH_JSON=\$(jq -cn --argjson lh "\$WG_UP_LAST_HS" '{interface_up: true, last_handshake: \$lh}')
        else
            UPSTREAM_HEALTH_JSON='{"interface_up": true, "last_handshake": null}'
        fi
    else
        # .name file exists but the utun device is gone — typically
        # after wg-quick up succeeded but wireguard-go crashed.
        UPSTREAM_HEALTH_JSON='{"interface_up": false, "last_handshake": null}'
    fi
fi

CAPABILITIES_JSON=\$(current_capabilities_json)
HOST_LAN_IP=\$(detect_host_lan_ip)
HOST_LAN_IP_JSON=\$(jq -Rn --arg v "\$HOST_LAN_IP" 'if (\$v | length) > 0 then \$v else null end')
INSTALLATION_ID_JSON=\$(jq -Rn --arg v "\$(cat ${INSTALLATION_ID_FILE} 2>/dev/null || echo "")" 'if (\$v | length) > 0 then \$v else null end')
TELEMETRY_JSON=\$(collect_device_telemetry_json)

HB_BODY=\$(jq -cn \\
    --arg endpoint "\$ENDPOINT" \\
    --argjson installation_id "\$INSTALLATION_ID_JSON" \\
    --argjson capabilities "\$CAPABILITIES_JSON" \\
    --argjson tx_bytes \$TX_BYTES \\
    --argjson rx_bytes \$RX_BYTES \\
    --argjson peers "\$PEERS_JSON" \\
    --argjson route_all_active \$ROUTE_ALL_ACTIVE \\
    --argjson host_lan_ip "\$HOST_LAN_IP_JSON" \\
    --argjson upstream_exit_health "\$UPSTREAM_HEALTH_JSON" \\
    --argjson telemetry "\$TELEMETRY_JSON" \\
    '{endpoint:\$endpoint, installation_id:\$installation_id, capabilities:\$capabilities,
      host_lan_ip:\$host_lan_ip, tx_bytes:\$tx_bytes, rx_bytes:\$rx_bytes, peers:\$peers,
      route_all_active:\$route_all_active, upstream_exit_health:\$upstream_exit_health,
      telemetry:\$telemetry}')

CURL_ARGS=( -sf -X POST -H "Content-Type: application/json" )
[[ -n "\$DEVICE_SECRET" ]] && CURL_ARGS+=( -H "X-Device-Secret: \$DEVICE_SECRET" )
RESPONSE=\$(curl "\${CURL_ARGS[@]}" \\
    -d "\$HB_BODY" \\
    "${BRAIN_URL}/api/v1/nodes/\${NODE_ID}/heartbeat" 2>/dev/null) || {
        if [[ "\${WG0_HEARTBEAT_STRICT:-0}" == "1" ]]; then
            exit 1
        fi
        exit 0
    }

if [[ "\$(echo "\$RESPONSE" | jq -r '.collect_device_telemetry // false' 2>/dev/null)" == "true" ]]; then
    echo "on" > "\$COLLECT_TELEMETRY_STATE"
else
    echo "off" > "\$COLLECT_TELEMETRY_STATE"
fi

# ── Config drift detection (device protocol v2) ──────────────────────────
# Heartbeat response carries \`config_version\`. If the brain advertises a
# newer version than the one we have on disk, fetch the full wg_config,
# substitute the local private key, and \`wg syncconf\` the utun interface.
REMOTE_CONFIG_VERSION=\$(echo "\$RESPONSE" | jq -r '.config_version // 0')
LOCAL_CONFIG_VERSION=\$(cat "${CONFIG_VERSION_FILE}" 2>/dev/null || echo 0)
if [[ "\$REMOTE_CONFIG_VERSION" -gt "\$LOCAL_CONFIG_VERSION" ]]; then
    CONFIG_CURL_ARGS=( -sf )
    [[ -n "\$DEVICE_SECRET" ]] && CONFIG_CURL_ARGS+=( -H "X-Device-Secret: \$DEVICE_SECRET" )
    NEW_CFG_JSON=\$(curl "\${CONFIG_CURL_ARGS[@]}" \\
        "${BRAIN_URL}/api/v1/nodes/\${NODE_ID}/config" 2>/dev/null || true)
    if [[ -n "\$NEW_CFG_JSON" ]]; then
        NEW_WG_CONFIG=\$(echo "\$NEW_CFG_JSON" | jq -r '.wg_config // empty')
        if [[ -n "\$NEW_WG_CONFIG" && -f "${PRIV_KEY_FILE}" ]]; then
            PRIV_KEY_VALUE=\$(cat "${PRIV_KEY_FILE}")
            TMP_CONF=\$(mktemp)
            echo "\$NEW_WG_CONFIG" \\
                | sed "s|# PrivateKey = <CONNECTOR_FILLS_THIS_IN>|PrivateKey = \${PRIV_KEY_VALUE}|" \\
                > "\$TMP_CONF"
            chmod 600 "\$TMP_CONF"
            mv -f "\$TMP_CONF" "${WG_CONF}"
            # macOS: wg syncconf targets the utun device, not the
            # logical wg0 alias. wg-quick strip is the same on macOS.
            "\$WG_BIN" syncconf "\$WG_REAL" <("\$WG_QUICK_BIN" strip "${WG_CONF}") 2>/dev/null || true
            echo "\$REMOTE_CONFIG_VERSION" > "${CONFIG_VERSION_FILE}"
            chmod 600 "${CONFIG_VERSION_FILE}"
        fi
    fi
fi

# Our own overlay /32 for use in same-LAN aliasing below.
OVERLAY_IP=\$(cat "\$OVERLAY_IP_FILE" 2>/dev/null | tr -d '[:space:]')

# add_peer_route: idempotently install a kernel route for one CIDR.
# macOS does not have \`ip route replace\`, so we delete-then-add. The brief
# gap is harmless because heartbeats run every 30s and pings retry.
add_peer_route() {
    local cidr="\$1"
    local iface="\$2"
    local ip="\${cidr%/*}"
    local prefix="\${cidr#*/}"
    [[ -z "\$ip" || -z "\$prefix" ]] && return
    if [[ "\$prefix" == "32" ]]; then
        route -nq delete -host "\$ip" 2>/dev/null
        route -nq add -host "\$ip" -interface "\$iface" 2>/dev/null
    else
        route -nq delete -net "\$cidr" 2>/dev/null
        route -nq add -net "\$cidr" -interface "\$iface" 2>/dev/null
    fi
}

del_peer_route() {
    local cidr="\$1"
    local ip="\${cidr%/*}"
    local prefix="\${cidr#*/}"
    [[ -z "\$ip" || -z "\$prefix" ]] && return
    if [[ "\$prefix" == "32" ]]; then
        route -nq delete -host "\$ip" 2>/dev/null
    else
        route -nq delete -net "\$cidr" 2>/dev/null
    fi
}

# get_phys_default: echoes "<iface> <gateway>" for the non-wg default route.
get_phys_default() {
    route -n get default 2>/dev/null | awk '
        /interface/ { iface = \$2 }
        /gateway/   { gw = \$2 }
        END { if (iface != "" && iface != "'"\$WG_REAL"'") print iface, gw }
    '
}

get_network_service_for_iface() {
    local iface="\$1"
    networksetup -listnetworkserviceorder 2>/dev/null | awk -v iface="\$iface" '
        /^\([^)]+\) / {
            svc=\$0
            sub(/^\([^)]+\) /, "", svc)
        }
        /Device: / {
            if (index(\$0, "Device: " iface) > 0) {
                print svc
                exit
            }
        }
    '
}

get_current_dns_servers() {
    local service="\$1"
    local out
    out="\$(networksetup -getdnsservers "\$service" 2>/dev/null || true)"
    if echo "\$out" | grep -q "There aren't any DNS Servers set on"; then
        return 0
    fi
    echo "\$out" | awk 'NF { print }'
}

set_service_dns_servers() {
    local service="\$1"
    shift || true
    if [[ "\$#" -eq 0 ]]; then
        networksetup -setdnsservers "\$service" Empty >/dev/null 2>&1 || true
    else
        networksetup -setdnsservers "\$service" "\$@" >/dev/null 2>&1 || true
    fi
}

restore_route_all_dns() {
    [[ -f "\$ROUTE_ALL_DNS_STATE" ]] || return 0
    local service csv
    IFS='|' read -r service csv < "\$ROUTE_ALL_DNS_STATE" || true
    [[ -n "\$service" ]] || return 0
    if [[ -z "\${csv:-}" ]]; then
        set_service_dns_servers "\$service"
    else
        IFS=',' read -r -a prev_dns <<< "\$csv"
        set_service_dns_servers "\$service" "\${prev_dns[@]}"
    fi
    rm -f "\$ROUTE_ALL_DNS_STATE"
}

# ── First pass: extract control-plane signals from peer list ──────────────
WANT_ROUTE_ALL=0
ROUTE_ALL_EP=""
ON_SAME_LAN=0
SAME_LAN_PEER_CIDRS=""
while read -r _p; do
    _a=\$(echo "\$_p" | jq -r '.allowed_ips')
    _sl=\$(echo "\$_p" | jq -r '.on_same_lan // false')
    if [[ "\$_a" == *"0.0.0.0/0"* ]]; then
        WANT_ROUTE_ALL=1
        ROUTE_ALL_EP=\$(echo "\$_p" | jq -r '.endpoint // empty')
    fi
    if [[ "\$_sl" == "true" ]]; then
        ON_SAME_LAN=1
        for _c in \$(echo "\$_a" | tr ',' ' '); do
            SAME_LAN_PEER_CIDRS="\$SAME_LAN_PEER_CIDRS \$_c"
        done
    fi
done < <(echo "\$RESPONSE" | jq -c '.peers[]' 2>/dev/null)

# ── Route-all (full VPN) state machine ──────────────────────────────────────
ROUTE_ALL_PREV=\$(cat "\$ROUTE_ALL_STATE" 2>/dev/null || echo "off")

if [[ "\$WANT_ROUTE_ALL" = "1" && "\$ON_SAME_LAN" = "0" && -n "\$ROUTE_ALL_EP" ]]; then
    # Install exception route for the host's public endpoint via the
    # current default gateway (physical link), then overlay the tunnel
    # with two /1 routes — more specific than /0 so the exception wins.
    # We skip route-all when on_same_lan is set: the tunnel can't be
    # trusted when we're on the host's LAN (hairpin NAT would break the
    # handshake) and the LAN already carries the traffic we care about.
    ENDPOINT_IP="\${ROUTE_ALL_EP%:*}"
    read -r DEFAULT_IFACE DEFAULT_GW < <(get_phys_default)
    if [[ -n "\$DEFAULT_GW" && -n "\$ENDPOINT_IP" ]]; then
        route -nq delete -host "\$ENDPOINT_IP" 2>/dev/null
        route -nq add -host "\$ENDPOINT_IP" "\$DEFAULT_GW" 2>/dev/null
    fi
    route -nq delete -net 0.0.0.0/1   2>/dev/null
    route -nq add    -net 0.0.0.0/1   -interface "\$WG_REAL" 2>/dev/null
    route -nq delete -net 128.0.0.0/1 2>/dev/null
    route -nq add    -net 128.0.0.0/1 -interface "\$WG_REAL" 2>/dev/null
    if [[ "\$ROUTE_ALL_PREV" != on* && -n "\$DEFAULT_IFACE" ]]; then
        PHYS_SERVICE="\$(get_network_service_for_iface "\$DEFAULT_IFACE")"
        if [[ -n "\$PHYS_SERVICE" ]]; then
            PREV_DNS="\$(get_current_dns_servers "\$PHYS_SERVICE" | paste -sd, -)"
            echo "\${PHYS_SERVICE}|\${PREV_DNS}" > "\$ROUTE_ALL_DNS_STATE"
            set_service_dns_servers "\$PHYS_SERVICE" 8.8.8.8 1.1.1.1
        fi
    fi
    echo "on|\${ENDPOINT_IP}" > "\$ROUTE_ALL_STATE"
elif [[ "\$ROUTE_ALL_PREV" == on* ]]; then
    # Transition OUT: tear down /1 routes + endpoint exception
    route -nq delete -net 0.0.0.0/1   2>/dev/null
    route -nq delete -net 128.0.0.0/1 2>/dev/null
    PREV_EP="\${ROUTE_ALL_PREV#*|}"
    [[ -n "\$PREV_EP" ]] && route -nq delete -host "\$PREV_EP" 2>/dev/null
    restore_route_all_dns
    echo "off" > "\$ROUTE_ALL_STATE"
fi

# ── Same-LAN state machine ─────────────────────────────────────────────────
# State format: "on|<iface>|<overlay-ip>" when aliased, "off" otherwise.
SAME_LAN_PREV=\$(cat "\$SAME_LAN_STATE" 2>/dev/null || echo "off")

if [[ "\$ON_SAME_LAN" = "1" && -n "\$OVERLAY_IP" ]]; then
    read -r PHYS_IFACE _ < <(get_phys_default)
    if [[ -n "\$PHYS_IFACE" && "\$SAME_LAN_PREV" != on* ]]; then
        # Transition IN: alias overlay IP on the physical interface so
        # LAN devices can ARP-resolve us at the overlay address.
        # macOS uses "ifconfig <iface> alias <ip> <mask>".
        ifconfig "\$PHYS_IFACE" alias "\$OVERLAY_IP" 255.255.255.255 2>/dev/null || true
        echo "on|\${PHYS_IFACE}|\${OVERLAY_IP}" > "\$SAME_LAN_STATE"
    fi
    # Remove any stale tunnel routes we previously installed for the
    # same-LAN peer's allowed_ips — physical LAN routing handles them.
    for _c in \$SAME_LAN_PEER_CIDRS; do
        del_peer_route "\$_c"
    done
elif [[ "\$SAME_LAN_PREV" == on* ]]; then
    # Transition OUT: remove alias. Per-peer loop below will reinstall
    # normal tunnel routes for the host on the next heartbeat.
    IFS='|' read -r _ PREV_IFACE PREV_OVERLAY <<< "\$SAME_LAN_PREV"
    if [[ -n "\$PREV_IFACE" && -n "\$PREV_OVERLAY" ]]; then
        ifconfig "\$PREV_IFACE" -alias "\$PREV_OVERLAY" 2>/dev/null || true
    fi
    echo "off" > "\$SAME_LAN_STATE"
fi

# ── BYO Exit: upstream WireGuard tunnel state machine (host nodes) ─────────
# The heartbeat response carries an optional \`upstream_exit\` object for host
# nodes. Brain ships the full wg_config inline; we persist it as
# /etc/wireguard/wg0-up.conf and \`wg-quick up\` it.
#
# macOS reachability model (tested setup: Mullvad + Sonoma/Sequoia behind
# consumer NAT): there's no \`ip rule fwmark\` or iptables equivalent, so
# when wg-quick takes over the default route, the host's own wg0 listener
# ends up sending its keepalives and handshake replies out through the
# upstream tunnel. The upstream provider's NAT allocates an outbound
# mapping, the discover sidecar observes the host's new post-NAT source
# address, and the brain pushes that Mullvad-mapped endpoint to every
# peer on the next heartbeat. PersistentKeepalive=25 on every peer keeps
# the mapping open, so inbound peer traffic reaches the host without any
# router port forwarding. This is the intended path on macOS and is
# verified in our tested setup — it assumes the upstream provider's NAT
# is friendly to UDP source-port preservation (Mullvad is). See
# docs/BYO_EXIT.md "Host-reachability policy routing" for the full flow.
UPSTREAM_STATE_FILE="${KEY_DIR}/upstream_exit_state"
UPSTREAM_CONF="/etc/wireguard/wg0-up.conf"

WANT_UPSTREAM_ID=\$(echo "\$RESPONSE" | jq -r '.upstream_exit.id // empty' 2>/dev/null)
WANT_UPSTREAM_CFG=\$(echo "\$RESPONSE" | jq -r '.upstream_exit.wg_config // empty' 2>/dev/null)
PREV_UPSTREAM_ID=\$(cat "\$UPSTREAM_STATE_FILE" 2>/dev/null || echo "off")

install_upstream_tunnel() {
    local cfg="\$1"
    umask 077
    # wg-quick on macOS insists on the .conf being the last path component
    # name, so we write it once and bring up by file path.
    echo "\$cfg" > "\$UPSTREAM_CONF"
    # wg-quick up handles interface creation + default-route takeover
    wg-quick up "\$UPSTREAM_CONF" 2>/dev/null || true
}

teardown_upstream_tunnel() {
    wg-quick down "\$UPSTREAM_CONF" 2>/dev/null || true
    # Clean up stale wireguard-go socket if the interface went away weirdly
    rm -f /var/run/wireguard/wg0-up.* 2>/dev/null || true
    rm -f "\$UPSTREAM_CONF"
}

if [[ -n "\$WANT_UPSTREAM_ID" && -n "\$WANT_UPSTREAM_CFG" ]]; then
    if [[ "\$PREV_UPSTREAM_ID" != "\$WANT_UPSTREAM_ID" ]]; then
        [[ "\$PREV_UPSTREAM_ID" != "off" ]] && teardown_upstream_tunnel
        install_upstream_tunnel "\$WANT_UPSTREAM_CFG"
        echo "\$WANT_UPSTREAM_ID" > "\$UPSTREAM_STATE_FILE"
    fi
elif [[ "\$PREV_UPSTREAM_ID" != "off" ]]; then
    teardown_upstream_tunnel
    echo "off" > "\$UPSTREAM_STATE_FILE"
fi

# ── Apply peer map updates + stale route cleanup ──────────────────────────
# wg set updates WireGuard state but does NOT add kernel routes. Install a
# route for each allowed_ips CIDR so packets actually reach the tunnel.
# 0.0.0.0/0 handled above via split-tunnel; peers flagged on_same_lan skip
# route installation entirely (LAN routing handles them).
#
# Stale route cleanup: track installed routes in a state file. On each
# heartbeat, diff old vs new and remove routes no longer in the peer list.
# This handles profile route policy changes (split→off, CIDR removal).

INSTALLED_ROUTES_FILE="${KEY_DIR}/installed_routes"
INSTALLED_ROUTES_IFACE_FILE="${KEY_DIR}/installed_routes_iface"
PREV_ROUTES=""
PREV_ROUTE_IFACE=\$(cat "\$INSTALLED_ROUTES_IFACE_FILE" 2>/dev/null || echo "")
[[ -f "\$INSTALLED_ROUTES_FILE" ]] && PREV_ROUTES=\$(cat "\$INSTALLED_ROUTES_FILE")
: > "\${INSTALLED_ROUTES_FILE}.new"

if [[ -n "\$PREV_ROUTES" && -n "\$PREV_ROUTE_IFACE" && "\$PREV_ROUTE_IFACE" != "\$WG_REAL" ]]; then
    echo "\$PREV_ROUTES" | while read -r old_cidr; do
        [[ -z "\$old_cidr" ]] && continue
        del_peer_route "\$old_cidr"
    done
    PREV_ROUTES=""
fi

echo "\$RESPONSE" | jq -c '.peers[]' 2>/dev/null | while read -r peer; do
    PUBKEY=\$(echo "\$peer" | jq -r '.public_key')
    ALLOWED=\$(echo "\$peer" | jq -r '.allowed_ips')
    EP=\$(echo "\$peer" | jq -r '.endpoint // empty')
    PEER_SAME_LAN=\$(echo "\$peer" | jq -r '.on_same_lan // false')
    if [[ -n "\$EP" ]]; then
        "\$WG_BIN" set "\$WG_REAL" peer "\$PUBKEY" allowed-ips "\$ALLOWED" endpoint "\$EP" persistent-keepalive 25
    else
        "\$WG_BIN" set "\$WG_REAL" peer "\$PUBKEY" allowed-ips "\$ALLOWED" persistent-keepalive 25
    fi
    [[ "\$PEER_SAME_LAN" == "true" ]] && continue
    echo "\$ALLOWED" | tr ',' '\\n' | tr -d ' ' | while read -r cidr; do
        [[ -z "\$cidr" || "\$cidr" == "0.0.0.0/0" ]] && continue
        echo "\$cidr" >> "\${INSTALLED_ROUTES_FILE}.new"
    done
done

echo "\$RESPONSE" | jq -c '.probe_peers // []' > "${KEY_DIR}/probe_peers" 2>/dev/null || true

# Shadow direct-probe peers: keep the direct path warm with endpoint +
# keepalive only, but never let it own any routes until the brain
# promotes it back to direct carrier ownership.
echo "\$RESPONSE" | jq -c '.probe_peers[]?' 2>/dev/null | while read -r peer; do
    PUBKEY=\$(echo "\$peer" | jq -r '.public_key // empty')
    EP=\$(echo "\$peer" | jq -r '.endpoint // empty')
    KEEPALIVE=\$(echo "\$peer" | jq -r '.persistent_keepalive // 25')
    [[ -z "\$PUBKEY" || -z "\$EP" ]] && continue
    "\$WG_BIN" set "\$WG_REAL" peer "\$PUBKEY" endpoint "\$EP" persistent-keepalive "\$KEEPALIVE"
done

# Reconcile kernel routes: add only newly-owned CIDRs, remove only stale ones.
if [[ -s "\${INSTALLED_ROUTES_FILE}.new" ]]; then
    sort -u "\${INSTALLED_ROUTES_FILE}.new" > "\${INSTALLED_ROUTES_FILE}.sorted" 2>/dev/null || true
    if [[ -n "\$PREV_ROUTES" ]]; then
        echo "\$PREV_ROUTES" | while read -r old_cidr; do
            [[ -z "\$old_cidr" ]] && continue
            if ! grep -qxF "\$old_cidr" "\${INSTALLED_ROUTES_FILE}.sorted" 2>/dev/null; then
                del_peer_route "\$old_cidr"
            fi
        done
    fi
    cat "\${INSTALLED_ROUTES_FILE}.sorted" | while read -r new_cidr; do
        [[ -z "\$new_cidr" ]] && continue
        if ! echo "\$PREV_ROUTES" | grep -qxF "\$new_cidr" 2>/dev/null; then
            add_peer_route "\$new_cidr" "\$WG_REAL"
        fi
    done
    mv -f "\${INSTALLED_ROUTES_FILE}.sorted" "\$INSTALLED_ROUTES_FILE" 2>/dev/null || true
    printf '%s' "\$WG_REAL" > "\$INSTALLED_ROUTES_IFACE_FILE"
    rm -f "\${INSTALLED_ROUTES_FILE}.new" 2>/dev/null || true
else
    # No routes installed this cycle — remove all previously tracked.
    if [[ -n "\$PREV_ROUTES" ]]; then
        echo "\$PREV_ROUTES" | while read -r old_cidr; do
            [[ -z "\$old_cidr" ]] && continue
            del_peer_route "\$old_cidr"
        done
    fi
    rm -f "\$INSTALLED_ROUTES_FILE" "\$INSTALLED_ROUTES_IFACE_FILE" "\${INSTALLED_ROUTES_FILE}.new" 2>/dev/null || true
fi

# ── Remove stale WireGuard peers ──────────────────────────────────────────
# If the brain stopped advertising a peer (e.g., native-LAN host-routed
# mode), remove it from WireGuard's crypto-key routing table.
RESPONSE_PUBKEYS=\$(
    echo "\$RESPONSE" \
        | jq -r '[(.peers[]?.public_key), (.probe_peers[]?.public_key)] | map(select(. != null and . != "")) | .[]' 2>/dev/null \
        | sort -u
)
WG_PUBKEYS=\$("\$WG_BIN" show "\$WG_REAL" peers 2>/dev/null | sort -u)
if [[ -n "\$WG_PUBKEYS" ]]; then
    echo "\$WG_PUBKEYS" | while read -r wg_pk; do
        [[ -z "\$wg_pk" ]] && continue
        if ! echo "\$RESPONSE_PUBKEYS" | grep -qxF "\$wg_pk"; then
            "\$WG_BIN" set "\$WG_REAL" peer "\$wg_pk" remove 2>/dev/null || true
        fi
    done
fi

# ── Multi-membership heartbeat pass (attached networks wg1+) ─────────────────
# Attached memberships share the primary's device_secret (same hash on
# the brain side). Minimal v1 heartbeat per attached iface so the brain
# keeps them online + tracks per-iface tx/rx. Host-mode state machines
# above stay primary-only.
ATTACHED_CAPABILITIES_JSON=\$(current_capabilities_json)
shopt -s nullglob
for att_dir in /etc/wireguard/wg* ; do
    [[ -d "\$att_dir" ]] || continue
    att_iface=\$(basename "\$att_dir")
    [[ "\$att_iface" == "${WG_IFACE}" ]] && continue
    att_node_id=\$(cat "\$att_dir/node_id" 2>/dev/null || true)
    att_brain=\$(cat "\$att_dir/brain_url" 2>/dev/null || true)
    [[ -z "\$att_node_id" || -z "\$att_brain" ]] && continue
    # macOS utun devices aren't enumerable by iface name; rely on
    # wg show knowing them as the conf alias.
    att_transfer=\$("\$WG_BIN" show "\$att_iface" transfer 2>/dev/null)
    [[ -z "\$att_transfer" ]] && continue
    att_tx=\$(echo "\$att_transfer" | awk '{sum += \$3} END {print sum+0}')
    att_rx=\$(echo "\$att_transfer" | awk '{sum += \$2} END {print sum+0}')
    att_payload=\$(jq -cn \\
        --argjson tx_bytes "\$att_tx" \\
        --argjson rx_bytes "\$att_rx" \\
        --argjson installation_id "\$INSTALLATION_ID_JSON" \\
        --argjson capabilities "\$ATTACHED_CAPABILITIES_JSON" \\
        '{tx_bytes:\$tx_bytes, rx_bytes:\$rx_bytes, installation_id:\$installation_id, capabilities:\$capabilities}')
    ATT_HEADERS=( -H "Content-Type: application/json" )
    [[ -n "\$DEVICE_SECRET" ]] && ATT_HEADERS+=( -H "X-Device-Secret: \$DEVICE_SECRET" )
    curl -sf -X POST "\${ATT_HEADERS[@]}" \\
        -d "\$att_payload" \\
        "\${att_brain%/}/api/v1/nodes/\${att_node_id}/heartbeat" \\
        >/dev/null 2>&1 || true
done
HBSCRIPT
    chmod +x "$HEARTBEAT_SCRIPT"
}

# ── Subcommand dispatch ───────────────────────────────────────────────────────
SUBCMD="${1:-}"

# Multi-membership subcommands (M2 roadmap, 2026-04-20). Mirrors
# connector.sh — see docs/CONNECTOR_MULTINETWORK_ROADMAP.md.
KNOWN_SUBCMDS=( enroll unenroll update rotate-secret attach detach list-networks )

is_known_subcmd() {
    local candidate="$1"
    local known
    for known in "${KNOWN_SUBCMDS[@]}"; do
        [[ "$candidate" == "$known" ]] && return 0
    done
    return 1
}

if ! is_known_subcmd "$SUBCMD"; then
    echo "Usage:"
    echo "  $0 enroll        <TOKEN> <BRAIN_URL> [NODE_NAME] [ROLE]"
    echo "  $0 update        <NEW_BRAIN_URL>"
    echo "  $0 unenroll      [BRAIN_URL]"
    echo "  $0 rotate-secret [BRAIN_URL]"
    echo "  $0 attach        <NETWORK_ID> <PAT> [BRAIN_URL] [ROLE] [NAME] [ROUTES_CSV]"
    echo "  $0 detach        <INTERFACE|NODE_ID|NETWORK_ID> <PAT>"
    echo "  $0 list-networks"
    exit 1
fi

shift  # consume subcommand

if [[ "$SUBCMD" == "unenroll" ]]; then
    BRAIN_URL="${1:-}"
    # If no brain URL given, try to read it from stored file
    if [[ -z "$BRAIN_URL" ]]; then
        for d in /etc/wireguard/wg0 /etc/wireguard/abslink; do
            [[ -f "$d/brain_url" ]] && BRAIN_URL=$(cat "$d/brain_url") && break
        done
    fi
    [[ -n "$BRAIN_URL" ]] || { echo "Usage: $0 unenroll [BRAIN_URL]"; echo "(Could not auto-detect brain URL — provide it explicitly)"; exit 1; }
elif [[ "$SUBCMD" == "update" ]]; then
    BRAIN_URL="${1:-}"
    [[ -n "$BRAIN_URL" ]] || { echo "Usage: $0 update <NEW_BRAIN_URL>"; exit 1; }
elif [[ "$SUBCMD" == "rotate-secret" ]]; then
    BRAIN_URL="${1:-}"
    if [[ -z "$BRAIN_URL" ]]; then
        for d in /etc/wireguard/wg0 /etc/wireguard/abslink; do
            [[ -f "$d/brain_url" ]] && BRAIN_URL=$(cat "$d/brain_url") && break
        done
    fi
    [[ -n "$BRAIN_URL" ]] || { echo "Usage: $0 rotate-secret [BRAIN_URL]"; exit 1; }
elif [[ "$SUBCMD" == "list-networks" ]]; then
    :  # no args
elif [[ "$SUBCMD" == "attach" ]]; then
    ATTACH_NETWORK_ID="${1:-}"
    ATTACH_PAT="${2:-}"
    ATTACH_BRAIN_URL="${3:-}"
    ATTACH_ROLE="${4:-client}"
    ATTACH_NODE_NAME="${5:-$(hostname -s)}"
    ATTACH_ROUTES_CSV="${6:-}"
    [[ -n "$ATTACH_NETWORK_ID" && -n "$ATTACH_PAT" ]] \
        || { echo "Usage: $0 attach <NETWORK_ID> <PAT> [BRAIN_URL] [ROLE] [NAME] [ROUTES_CSV]"; exit 1; }
elif [[ "$SUBCMD" == "detach" ]]; then
    DETACH_TARGET="${1:-}"
    DETACH_PAT="${2:-}"
    [[ -n "$DETACH_TARGET" && -n "$DETACH_PAT" ]] \
        || { echo "Usage: $0 detach <INTERFACE|NODE_ID|NETWORK_ID> <PAT>"; exit 1; }
else
    TOKEN="${1:-}"
    BRAIN_URL="${2:-}"
    NODE_NAME="${3:-$(hostname -s)}"
    ROLE="${4:-client}"
    [[ -n "$TOKEN" && -n "$BRAIN_URL" ]] || {
        echo "Usage: $0 enroll <TOKEN> <BRAIN_URL> [NODE_NAME] [ROLE]"
        exit 1
    }
fi

BRAIN_URL="${BRAIN_URL%/}"

# ── ROTATE-SECRET ─────────────────────────────────────────────────────────────
if [[ "$SUBCMD" == "rotate-secret" ]]; then
    [[ -f "$NODE_ID_FILE" ]] || die "No node_id found. This system does not appear to be enrolled."
    NODE_ID=$(cat "$NODE_ID_FILE")
    log "Rotating device secret for node ${NODE_ID} at ${BRAIN_URL}"

    CUR_SECRET=$(cat "$DEVICE_SECRET_FILE" 2>/dev/null || true)
    ROTATE_ARGS=( -sf -X POST -H "Content-Type: application/json" )
    [[ -n "$CUR_SECRET" ]] && ROTATE_ARGS+=( -H "X-Device-Secret: $CUR_SECRET" )
    RESP=$(curl "${ROTATE_ARGS[@]}" "${BRAIN_URL}/api/v1/nodes/${NODE_ID}/rotate-secret" -d '{}' 2>/dev/null || true)
    if [[ -z "$RESP" ]]; then
        warn "rotate-secret with current secret failed; retrying legacy recovery path"
        RESP=$(curl -sf -X POST -H "Content-Type: application/json" \
            "${BRAIN_URL}/api/v1/nodes/${NODE_ID}/rotate-secret" -d '{}' 2>/dev/null) \
            || die "rotate-secret request failed — brain unreachable or recovery path rejected."
    fi

    NEW_SECRET=$(echo "$RESP" | jq -r '.device_secret // empty')
    [[ -n "$NEW_SECRET" ]] || die "Brain returned no device_secret in rotate response: $RESP"

    TMP_SECRET=$(mktemp "$KEY_DIR/.device_secret.XXXXXX")
    printf '%s' "$NEW_SECRET" > "$TMP_SECRET"
    chmod 600 "$TMP_SECRET"
    mv -f "$TMP_SECRET" "$DEVICE_SECRET_FILE"

    log "Device secret rotated successfully. Future heartbeats will use the new secret."
    exit 0
fi

# ── LIST-NETWORKS ─────────────────────────────────────────────────────────────
# List every membership held by this macOS installation (primary wg0 and
# any attached wgN). Same shape as connector.sh list-networks.
if [[ "$SUBCMD" == "list-networks" ]]; then
    printf '%-10s %-38s %-20s %s\n' "IFACE" "NODE_ID" "OVERLAY_IP" "BRAIN_URL"
    printf '%-10s %-38s %-20s %s\n' "-----" "-------" "----------" "---------"
    shopt -s nullglob
    for dir in /etc/wireguard/wg* ; do
        [[ -d "$dir" ]] || continue
        iface=$(basename "$dir")
        nid=$(cat "${dir}/node_id" 2>/dev/null || true)
        oip=$(cat "${dir}/overlay_ip" 2>/dev/null || true)
        burl=$(cat "${dir}/brain_url" 2>/dev/null || true)
        [[ -z "$nid" ]] && continue
        printf '%-10s %-38s %-20s %s\n' "$iface" "${nid:-?}" "${oip:--}" "${burl:--}"
    done
    exit 0
fi

# ── ATTACH ────────────────────────────────────────────────────────────────────
# Attach this installation to an ADDITIONAL network. See connector.sh's
# ATTACH section for the full protocol narrative — this mirror uses the
# same endpoints and state layout. The macOS-specific bit is launchd
# instead of systemd for keeping wg-quick@wgN alive across reboots.
if [[ "$SUBCMD" == "attach" ]]; then
    [[ -f "$DEVICE_ID_FILE" ]] \
        || die "Primary wg0 isn't enrolled yet. Run '$0 enroll ...' first."
    DEVICE_ID=$(cat "$DEVICE_ID_FILE")
    DEVICE_SECRET=$(cat "$DEVICE_SECRET_FILE" 2>/dev/null || true)
    [[ -n "$DEVICE_SECRET" ]] || die "Missing device_secret — run '$0 rotate-secret' first."

    if [[ -z "$ATTACH_BRAIN_URL" ]]; then
        ATTACH_BRAIN_URL=$(cat /etc/wireguard/wg0/brain_url 2>/dev/null || true)
    fi
    [[ -n "$ATTACH_BRAIN_URL" ]] || die "Could not determine brain URL. Pass it as the third arg."
    ATTACH_BRAIN_URL="${ATTACH_BRAIN_URL%/}"

    next_iface=""
    for n in {1..63}; do
        candidate="wg${n}"
        if [[ ! -e "/etc/wireguard/${candidate}.conf" && ! -d "/etc/wireguard/${candidate}" ]]; then
            next_iface="$candidate"
            break
        fi
    done
    [[ -n "$next_iface" ]] || die "No free wg interface names between wg1 and wg63."
    ATTACH_DIR="/etc/wireguard/${next_iface}"
    mkdir -p "$ATTACH_DIR"
    chmod 700 "$ATTACH_DIR"

    log "Attaching network ${ATTACH_NETWORK_ID} on ${next_iface} (brain=${ATTACH_BRAIN_URL})..."

    wg genkey | tee "${ATTACH_DIR}/private.key" | wg pubkey > "${ATTACH_DIR}/public.key"
    chmod 600 "${ATTACH_DIR}/private.key"
    ATTACH_PRIV=$(cat "${ATTACH_DIR}/private.key")
    ATTACH_PUB=$(cat "${ATTACH_DIR}/public.key")

    REQ_BODY=$(jq -cn \
        --arg network_id "$ATTACH_NETWORK_ID" \
        --arg desired_role "$ATTACH_ROLE" \
        --arg desired_name "$ATTACH_NODE_NAME" \
        '{network_id:$network_id, desired_role:$desired_role, desired_name:$desired_name}')
    CREATE_RESP=$(curl -sf -X POST \
        -H "Authorization: Bearer ${ATTACH_PAT}" \
        -H "Content-Type: application/json" \
        -d "$REQ_BODY" \
        "${ATTACH_BRAIN_URL}/api/v1/devices/${DEVICE_ID}/memberships") \
        || { rm -rf "$ATTACH_DIR"; die "Attach request failed. Check PAT + NETWORK_ID + that the brain has seen this device advertise multi_membership_v1."; }

    REQ_ID=$(echo "$CREATE_RESP" | jq -r --arg nid "$ATTACH_NETWORK_ID" '
        (.pending_membership_requests // [])
        | map(select(.network_id == $nid and .status == "pending"))
        | sort_by(.created_at) | last | .id // empty')
    [[ -n "$REQ_ID" ]] || { rm -rf "$ATTACH_DIR"; die "Brain did not return a pending membership request id: $CREATE_RESP"; }

    ATTACH_PUBLIC_IP=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "")
    ATTACH_ENDPOINT=""
    [[ -n "$ATTACH_PUBLIC_IP" ]] && ATTACH_ENDPOINT="${ATTACH_PUBLIC_IP}:51820"
    if [[ -n "$ATTACH_ROUTES_CSV" ]]; then
        ATTACH_ROUTES_JSON=$(echo "$ATTACH_ROUTES_CSV" | jq -R 'split(",") | map(select(length > 0) | gsub("^ +| +$"; ""))')
    else
        ATTACH_ROUTES_JSON="[]"
    fi
    FULFILL_BODY=$(jq -cn \
        --arg public_key "$ATTACH_PUB" \
        --arg node_name "$ATTACH_NODE_NAME" \
        --arg os_type "macos" \
        --arg endpoint "$ATTACH_ENDPOINT" \
        --argjson advertised_routes "$ATTACH_ROUTES_JSON" \
        '{public_key:$public_key, node_name:$node_name, os_type:$os_type, endpoint:($endpoint|select(length>0)), advertised_routes:$advertised_routes}')

    FULFILL_RESP=$(curl -sf -X POST \
        -H "X-Device-Secret: ${DEVICE_SECRET}" \
        -H "Wg0-Protocol-Version: 2" \
        -H "Content-Type: application/json" \
        -d "$FULFILL_BODY" \
        "${ATTACH_BRAIN_URL}/api/v2/installations/${DEVICE_ID}/memberships/${REQ_ID}/fulfill") \
        || { rm -rf "$ATTACH_DIR"; die "Fulfillment failed. The pending request still exists brain-side — retry or delete it from the dashboard."; }

    ATTACH_NODE_ID=$(echo "$FULFILL_RESP" | jq -r '.node_id')
    ATTACH_OVERLAY=$(echo "$FULFILL_RESP" | jq -r '.overlay_ip')
    ATTACH_WG_CONFIG=$(echo "$FULFILL_RESP" | jq -r '.wg_config')
    [[ -n "$ATTACH_NODE_ID" && "$ATTACH_NODE_ID" != "null" ]] \
        || { rm -rf "$ATTACH_DIR"; die "Fulfillment response missing node_id: $FULFILL_RESP"; }

    echo "$ATTACH_NODE_ID"      > "${ATTACH_DIR}/node_id";     chmod 600 "${ATTACH_DIR}/node_id"
    echo "$ATTACH_NETWORK_ID"   > "${ATTACH_DIR}/network_id";  chmod 600 "${ATTACH_DIR}/network_id"
    echo "$ATTACH_BRAIN_URL"    > "${ATTACH_DIR}/brain_url";   chmod 600 "${ATTACH_DIR}/brain_url"
    echo "${ATTACH_OVERLAY%/*}" > "${ATTACH_DIR}/overlay_ip";  chmod 600 "${ATTACH_DIR}/overlay_ip"

    ATTACH_CONF="/etc/wireguard/${next_iface}.conf"
    echo "$ATTACH_WG_CONFIG" \
        | sed "s|# PrivateKey = <CONNECTOR_FILLS_THIS_IN>|PrivateKey = ${ATTACH_PRIV}|" \
        > "$ATTACH_CONF"
    chmod 600 "$ATTACH_CONF"

    # Bring the tunnel up. macOS uses wg-quick directly (via brew
    # wireguard-tools); reboot-persistence is handled by a launchd plist
    # that parallels the macOS primary path — documented in the macOS
    # diagnostics plan.
    wg-quick up "$ATTACH_CONF" || die "wg-quick up ${ATTACH_CONF} failed."

    log "Attached! ${next_iface} → ${ATTACH_OVERLAY} (node_id=${ATTACH_NODE_ID})"
    log "Note: heartbeats for attached memberships need the per-interface timer (coming in a follow-up)."
    exit 0
fi

# ── DETACH ────────────────────────────────────────────────────────────────────
if [[ "$SUBCMD" == "detach" ]]; then
    det_iface=""
    if [[ -d "/etc/wireguard/${DETACH_TARGET}" ]]; then
        det_iface="$DETACH_TARGET"
    else
        shopt -s nullglob
        for dir in /etc/wireguard/wg* ; do
            [[ -d "$dir" ]] || continue
            it=$(basename "$dir")
            [[ "$it" == "wg0" ]] && continue
            if [[ "$(cat "${dir}/node_id" 2>/dev/null || true)" == "$DETACH_TARGET" ]] \
                || [[ "$(cat "${dir}/network_id" 2>/dev/null || true)" == "$DETACH_TARGET" ]]; then
                det_iface="$it"
                break
            fi
        done
    fi
    [[ -n "$det_iface" ]] || die "Could not resolve '${DETACH_TARGET}' to an attached membership. Run '$0 list-networks' to inspect state."
    [[ "$det_iface" == "wg0" ]] && die "wg0 is the primary installation. Use '$0 unenroll' to remove it."

    det_dir="/etc/wireguard/${det_iface}"
    det_node_id=$(cat "${det_dir}/node_id" 2>/dev/null || true)
    det_brain=$(cat "${det_dir}/brain_url" 2>/dev/null || cat /etc/wireguard/wg0/brain_url 2>/dev/null || true)
    det_device_id=$(cat "$DEVICE_ID_FILE" 2>/dev/null || true)

    if [[ -n "$det_node_id" && -n "$det_brain" && -n "$det_device_id" ]]; then
        curl -sf -X DELETE \
            -H "Authorization: Bearer ${DETACH_PAT}" \
            "${det_brain%/}/api/v1/devices/${det_device_id}/memberships/${det_node_id}" \
            >/dev/null 2>&1 || warn "Brain-side detach failed; continuing with local teardown."
    fi

    if ifconfig "$det_iface" >/dev/null 2>&1; then
        wg-quick down "/etc/wireguard/${det_iface}.conf" 2>/dev/null || true
    fi
    rm -f "/etc/wireguard/${det_iface}.conf"
    rm -rf "${det_dir}"

    log "Detached ${det_iface} (node_id=${det_node_id:-unknown})."
    exit 0
fi

# ── UPDATE ────────────────────────────────────────────────────────────────────
if [[ "$SUBCMD" == "update" ]]; then
    log "wg0 update — migrating to brain at ${BRAIN_URL}"

    # ── 1. Detect current key dir (legacy or new) ────────────────────────────
    OLD_KEY_DIR=""
    if [[ -d /etc/wireguard/abslink ]]; then
        OLD_KEY_DIR="/etc/wireguard/abslink"
    fi

    if [[ -n "$OLD_KEY_DIR" && "$OLD_KEY_DIR" != "$KEY_DIR" ]]; then
        log "Migrating key directory: ${OLD_KEY_DIR} → ${KEY_DIR}"
        mv "$OLD_KEY_DIR" "$KEY_DIR"
    fi

    NODE_ID_FILE="${KEY_DIR}/node_id"
    [[ -f "$NODE_ID_FILE" ]] || die "No node_id found. This system does not appear to be enrolled."
    NODE_ID=$(cat "$NODE_ID_FILE")
    log "Node ID: ${NODE_ID}"

    # ── 2. Store brain URL for future reference ──────────────────────────────
    echo "$BRAIN_URL" > "${KEY_DIR}/brain_url"
    chmod 600 "${KEY_DIR}/brain_url"

    # Propagate the new brain URL to any attached memberships too
    # (wg1/, wg2/, ...) so `update` rehomes the whole installation.
    shopt -s nullglob
    for att_dir in /etc/wireguard/wg* ; do
        [[ -d "$att_dir" ]] || continue
        [[ "$(basename "$att_dir")" == "wg0" ]] && continue
        [[ -f "$att_dir/brain_url" ]] || continue
        echo "$BRAIN_URL" > "$att_dir/brain_url"
        chmod 600 "$att_dir/brain_url"
    done

    # ── 3. Migrate legacy heartbeat script name ──────────────────────────────
    OLD_HB="/usr/local/bin/abslink-heartbeat"
    if [[ -f "$OLD_HB" && "$OLD_HB" != "$HEARTBEAT_SCRIPT" ]]; then
        log "Renaming heartbeat script: abslink-heartbeat → $(basename $HEARTBEAT_SCRIPT)"
        mv "$OLD_HB" "$HEARTBEAT_SCRIPT"
    fi

    # ── 4. Rewrite heartbeat script from current template ────────────────────
    # We don't sed-patch — too fragile. Just regenerate the whole script with
    # the latest brain URL, route logic, TX/RX reporting, etc.
    write_heartbeat_script
    log "Rewrote heartbeat script with latest template (brain=${BRAIN_URL})"

    # ── 5. Migrate legacy launchd plists ─────────────────────────────────────
    OLD_HB_PLIST="/Library/LaunchDaemons/com.abslink.heartbeat.plist"
    OLD_WG_PLIST="/Library/LaunchDaemons/com.abslink.wireguard.plist"

    if [[ -f "$OLD_HB_PLIST" ]]; then
        log "Migrating heartbeat launchd plist: com.abslink → io.wg0"
        launchctl unload "$OLD_HB_PLIST" 2>/dev/null || true
        # Rewrite with new label and new heartbeat script path
        sed 's|com\.abslink\.heartbeat|io.wg0.heartbeat|g; s|abslink-heartbeat|wg0-heartbeat|g' \
            "$OLD_HB_PLIST" > "$LAUNCHDAEMON_PLIST"
        rm -f "$OLD_HB_PLIST"
        launchctl load "$LAUNCHDAEMON_PLIST"
        log "Heartbeat daemon reloaded as io.wg0.heartbeat"
    elif [[ -f "$LAUNCHDAEMON_PLIST" ]]; then
        # Just reload with the new heartbeat script path in case it was updated
        launchctl unload "$LAUNCHDAEMON_PLIST" 2>/dev/null || true
        launchctl load "$LAUNCHDAEMON_PLIST"
        log "Heartbeat daemon reloaded"
    fi

    if [[ -f "$OLD_WG_PLIST" ]]; then
        log "Migrating WireGuard watchdog plist: com.abslink → io.wg0"
        launchctl unload "$OLD_WG_PLIST" 2>/dev/null || true
        sed 's|com\.abslink\.wireguard|io.wg0.wireguard|g; s|abslink-|wg0-|g' \
            "$OLD_WG_PLIST" > "$WG_WATCHDOG_PLIST"
        rm -f "$OLD_WG_PLIST"
        launchctl load "$WG_WATCHDOG_PLIST"
        log "WireGuard watchdog reloaded as io.wg0.wireguard"
    fi

    # ── 6. Migrate legacy postup/predown scripts ────────────────────────────
    for pair in "abslink-postup:wg0-postup" "abslink-predown:wg0-predown"; do
        old="/usr/local/bin/${pair%%:*}"
        new="/usr/local/bin/${pair##*:}"
        if [[ -f "$old" && "$old" != "$new" ]]; then
            mv "$old" "$new"
        fi
    done
    # Update PostUp/PreDown references in WireGuard config
    if [[ -f "$WG_CONF" ]]; then
        sed -i '' 's|abslink-postup|wg0-postup|g; s|abslink-predown|wg0-predown|g' "$WG_CONF"
    fi

    # ── 7. Install/update wg0 CLI ────────────────────────────────────────────
    if curl -fsSL "${BRAIN_URL%/api*}/wg0-status.sh" -o /usr/local/bin/wg0 2>/dev/null \
       || curl -fsSL "https://wg0.io/wg0-status.sh" -o /usr/local/bin/wg0 2>/dev/null; then
        chmod +x /usr/local/bin/wg0
        log "Updated wg0 CLI tool"
    fi
    # Remove old abslink CLI if present
    rm -f /usr/local/bin/abslink 2>/dev/null || true

    # ── 8. Force an immediate heartbeat to verify ────────────────────────────
    log "Running heartbeat to verify connectivity..."
    if WG0_HEARTBEAT_STRICT=1 bash "$HEARTBEAT_SCRIPT" 2>/dev/null; then
        log "Heartbeat succeeded — connected to ${BRAIN_URL}"
    else
        warn "Heartbeat failed — check that ${BRAIN_URL} is reachable"
    fi

    log ""
    log "Update complete."
    log "  Brain URL:  ${BRAIN_URL}"
    log "  Node ID:    ${NODE_ID}"
    log "  Key dir:    ${KEY_DIR}"
    log ""
    log "Run 'wg0 status' to verify tunnel health."
    exit 0
fi

# ── UNENROLL ──────────────────────────────────────────────────────────────────
if [[ "$SUBCMD" == "unenroll" ]]; then
    log "Starting unenroll from Brain at ${BRAIN_URL} ..."

    if [[ ! -f "$NODE_ID_FILE" ]]; then
        die "No node_id found at ${NODE_ID_FILE}. This system does not appear to be enrolled."
    fi
    NODE_ID=$(cat "$NODE_ID_FILE")
    log "Node ID: ${NODE_ID}"

    log "Notifying Brain to remove node..."
    DEVICE_SECRET=$(cat "$DEVICE_SECRET_FILE" 2>/dev/null || true)
    UNENROLL_ARGS=( -sf -X DELETE )
    [[ -n "$DEVICE_SECRET" ]] && UNENROLL_ARGS+=( -H "X-Device-Secret: $DEVICE_SECRET" )
    if curl "${UNENROLL_ARGS[@]}" "${BRAIN_URL}/api/v1/nodes/${NODE_ID}/self" >/dev/null 2>&1; then
        log "Brain confirmed node removal."
    else
        warn "Brain request failed (unreachable?). Continuing local cleanup."
    fi

    log "Bringing down WireGuard interface ${WG_IFACE}..."
    if [[ -f "$WG_CONF" ]]; then
        wg-quick down "$WG_CONF" 2>/dev/null || true
    fi
    # wg-quick down can fail if the conf was already removed or the interface
    # was left orphaned by a previous failed enroll. Force-remove the utun too.
    UTUN=$(wg show "$WG_IFACE" 2>/dev/null | awk '/^interface:/{print $2}' || true)
    if [[ -z "$UTUN" ]]; then
        # Fallback: find the utun holding our WireGuard socket
        UTUN=$(ifconfig -l | tr ' ' '\n' | grep '^utun' | while read iface; do
            wg show "$iface" 2>/dev/null | grep -q 'listen port' && echo "$iface" && break
        done || true)
    fi
    [[ -n "$UTUN" ]] && ifconfig "$UTUN" destroy 2>/dev/null || true

    if [[ -f "$WG_WATCHDOG_PLIST" ]]; then
        log "Removing launchd WireGuard watchdog daemon..."
        launchctl unload "$WG_WATCHDOG_PLIST" 2>/dev/null || true
        rm -f "$WG_WATCHDOG_PLIST"
    fi

    if [[ -f "$LAUNCHDAEMON_PLIST" ]]; then
        log "Removing launchd heartbeat daemon..."
        launchctl unload "$LAUNCHDAEMON_PLIST" 2>/dev/null || true
        rm -f "$LAUNCHDAEMON_PLIST"
    fi

    # Flush NAT rules added by native host mode
    if [[ -f "$PREDOWN_SCRIPT" ]]; then
        bash "$PREDOWN_SCRIPT" 2>/dev/null || true
    fi

    rm -f "$HEARTBEAT_SCRIPT" "$POSTUP_SCRIPT" "$PREDOWN_SCRIPT"
    rm -f /var/run/wireguard/${WG_IFACE}.sock 2>/dev/null || true
    rm -f "$WG_CONF"
    rm -rf "$KEY_DIR"
    log "Unenroll complete. This node has been removed from wg0."
    exit 0
fi

# ── ENROLL ────────────────────────────────────────────────────────────────────
log "wg0 macOS Connector — arch=${ARCH}, Homebrew=${BREW_PREFIX}"

# ── Homebrew check ────────────────────────────────────────────────────────────
if [[ ! -x "$BREW" ]]; then
    log "Homebrew not found at ${BREW_PREFIX}. Installing Homebrew..."
    # Run install as the actual user (not root) — Homebrew refuses to run as root
    REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo $USER)}"
    sudo -u "$REAL_USER" /bin/bash -c \
        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
        || die "Homebrew installation failed."
    log "Homebrew installed."
fi

# ── Install missing dependencies ──────────────────────────────────────────────
REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo $USER)}"
for pkg in wireguard-tools jq; do
    if ! sudo -u "$REAL_USER" "$BREW" list "$pkg" >/dev/null 2>&1; then
        log "Installing ${pkg} via Homebrew..."
        sudo -u "$REAL_USER" "$BREW" install "$pkg" \
            || die "Failed to install ${pkg}. Run 'brew install ${pkg}' manually."
    fi
done

# Add Homebrew bin to PATH for wg / wg-quick
export PATH="${BREW_PREFIX}/bin:${BREW_PREFIX}/sbin:$PATH"

# ── Dependency check ──────────────────────────────────────────────────────────
for cmd in wg wg-quick curl jq; do
    command -v "$cmd" >/dev/null 2>&1 || die "Required command '${cmd}' not found after install attempt."
done

# ── Directory setup ───────────────────────────────────────────────────────────
mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"

# ── Key generation ────────────────────────────────────────────────────────────
if [[ ! -f "$PRIV_KEY_FILE" ]]; then
    log "Generating WireGuard keypair..."
    wg genkey | tee "$PRIV_KEY_FILE" | wg pubkey > "$PUB_KEY_FILE"
    chmod 600 "$PRIV_KEY_FILE"
fi
PRIV_KEY=$(cat "$PRIV_KEY_FILE")
PUB_KEY=$(cat "$PUB_KEY_FILE")
INSTALLATION_ID=$(get_or_create_installation_id)
log "Public key: ${PUB_KEY}"

# ── Detect public endpoint ────────────────────────────────────────────────────
PUBLIC_IP=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "")
ENDPOINT=""
[[ -n "$PUBLIC_IP" ]] && ENDPOINT="${PUBLIC_IP}:51820"

# ── Enrollment ────────────────────────────────────────────────────────────────
if [[ ! -f "$NODE_ID_FILE" ]]; then
    log "Enrolling node '${NODE_NAME}' (role=${ROLE}, os_type=macos) with Brain at ${BRAIN_URL} ..."

    PAYLOAD=$(cat <<EOF
{
    "token": "${TOKEN}",
    "installation_id": "${INSTALLATION_ID}",
    "public_key": "${PUB_KEY}",
    "node_name": "${NODE_NAME}",
    "os_type": "macos",
    "role": "${ROLE}",
    "advertised_routes": [],
    "endpoint": "${ENDPOINT}"
}
EOF
)

    ENROLL_RESPONSE=$(curl -sf -X POST \
        -H "Content-Type: application/json" \
        -d "$PAYLOAD" \
        "${BRAIN_URL}/api/v1/enroll/register") \
        || die "Enrollment failed. Check TOKEN and BRAIN_URL."

    DEVICE_ID=$(echo "$ENROLL_RESPONSE" | jq -r '.device_id // empty')
    NODE_ID=$(echo "$ENROLL_RESPONSE" | jq -r '.node_id')
    OVERLAY_IP=$(echo "$ENROLL_RESPONSE" | jq -r '.overlay_ip')
    WG_CONFIG=$(echo "$ENROLL_RESPONSE" | jq -r '.wg_config')
    NETWORK_TYPE=$(echo "$ENROLL_RESPONSE" | jq -r '.network_type // "overlay"')
    # Device protocol v2 secret. Empty when brain is still v1-only.
    DEVICE_SECRET=$(echo "$ENROLL_RESPONSE" | jq -r '.device_secret // empty')

    echo "$NODE_ID" > "$NODE_ID_FILE"
    chmod 600 "$NODE_ID_FILE"
    if [[ -n "$DEVICE_ID" ]]; then
        printf '%s' "$DEVICE_ID" > "$DEVICE_ID_FILE"
        chmod 600 "$DEVICE_ID_FILE"
    fi
    echo "$BRAIN_URL" > "${KEY_DIR}/brain_url"
    chmod 600 "${KEY_DIR}/brain_url"
    if [[ -n "$DEVICE_SECRET" ]]; then
        printf '%s' "$DEVICE_SECRET" > "$DEVICE_SECRET_FILE"
        chmod 600 "$DEVICE_SECRET_FILE"
    fi
    # Bare overlay IP (no /prefix) — used by the heartbeat's same-LAN
    # state machine to alias the overlay /32 on the physical interface.
    echo "${OVERLAY_IP%/*}" > "${KEY_DIR}/overlay_ip"
    chmod 600 "${KEY_DIR}/overlay_ip"

    # ── macOS config post-processing ─────────────────────────────────────────
    #
    # 1. Strip Linux-specific PostUp/PreDown lines (reference /proc or `ip route`).
    #    These will cause wg-quick to fail on macOS.
    #
    # 2. For host role: the brain generates Address = x.x.x.x/NN (gateway subnet prefix).
    #    On macOS, that competing /24 route conflicts with the physical Ethernet interface
    #    already on the same subnet. We rewrite to /32 so only a host route is added,
    #    then enable IP forwarding via a macOS-safe PostUp.
    #
    # 3. For client role: Address is already /32 from the brain — no change needed.

    # Strip Linux PostUp/PreDown
    PROCESSED_CONFIG=$(echo "$WG_CONFIG" | grep -v '^PostUp' | grep -v '^PreDown')

    if [[ "$ROLE" == "host" && "$NETWORK_TYPE" == "native" ]]; then
        log "Native host mode: rewriting Address to /32 and adding macOS IP forwarding + NAT PostUp."

        # Extract the gateway subnet from the original Address line BEFORE rewriting to /32.
        # e.g. "Address = 192.168.1.2/24"  →  GW_SUBNET="192.168.1.0/24"
        ORIG_ADDR=$(echo "$PROCESSED_CONFIG" | awk '/^Address[[:space:]]*=/{print $3}')
        GW_SUBNET=$(python3 -c "import ipaddress; print(str(ipaddress.IPv4Network('${ORIG_ADDR}', strict=False)))" 2>/dev/null || echo "")
        [[ -z "$GW_SUBNET" ]] && die "Could not determine gateway subnet from Address '${ORIG_ADDR}'."
        log "Gateway subnet: ${GW_SUBNET}"

        # Rewrite /NN → /32 on the Address line (avoids competing route with physical LAN)
        PROCESSED_CONFIG=$(echo "$PROCESSED_CONFIG" | \
            sed 's/^\(Address = [0-9][0-9.]*\)\/[0-9]*/\1\/32/')

        # Write PostUp script: IP forwarding + pfctl NAT so LAN devices can reply to tunnel clients.
        # net.inet.proxyarp does not exist on modern macOS; NAT is the reliable alternative.
        cat > "$POSTUP_SCRIPT" << POSTUPEOF
#!/bin/bash
sysctl -w net.inet.ip.forwarding=1
PHYS=\$(route get default | awk '/interface:/{print \$2}')
printf "nat on %s from ${GW_SUBNET} to any -> (%s)\npass all\n" "\$PHYS" "\$PHYS" | pfctl -f - -e 2>/dev/null || true
POSTUPEOF
        chmod +x "$POSTUP_SCRIPT"

        # Write PreDown script: remove NAT rules when interface goes down.
        cat > "$PREDOWN_SCRIPT" << PREDOWNEOF
#!/bin/bash
pfctl -F nat 2>/dev/null || true
PREDOWNEOF
        chmod +x "$PREDOWN_SCRIPT"

        # Insert PostUp/PreDown references into the config after ListenPort line
        PROCESSED_CONFIG=$(echo "$PROCESSED_CONFIG" | \
            awk -v postup="$POSTUP_SCRIPT" -v predown="$PREDOWN_SCRIPT" \
            '/^ListenPort/{print; print "PostUp = " postup; print "PreDown = " predown; next}1')
    fi

    # Substitute private key placeholder
    PROCESSED_CONFIG=$(echo "$PROCESSED_CONFIG" | \
        sed "s|# PrivateKey = <CONNECTOR_FILLS_THIS_IN>|PrivateKey = ${PRIV_KEY}|")

    # Write config
    mkdir -p "$(dirname "$WG_CONF")"
    echo "$PROCESSED_CONFIG" > "$WG_CONF"
    chmod 600 "$WG_CONF"

    log "Enrolled! Assigned IP: ${OVERLAY_IP} | Node ID: ${NODE_ID} | Network type: ${NETWORK_TYPE}"
fi

NODE_ID=$(cat "$NODE_ID_FILE")

# ── Bring up WireGuard ────────────────────────────────────────────────────────
if ! wg show "$WG_IFACE" >/dev/null 2>&1; then
    # Clean up stale socket if wireguard-go died without proper teardown.
    # Without this, wg-quick up fails with "'wg0' already exists".
    rm -f "/var/run/wireguard/${WG_IFACE}.sock" 2>/dev/null || true
    log "Bringing up WireGuard interface ${WG_IFACE}..."
    wg-quick up "$WG_CONF" || die "Failed to bring up WireGuard. Check /var/log/system.log."
fi
log "Interface ${WG_IFACE} is up."

# ── Heartbeat script ──────────────────────────────────────────────────────────
write_heartbeat_script

# ── Install heartbeat — launchd daemon ───────────────────────────────────────
log "Installing launchd heartbeat daemon (every ${HEARTBEAT_INTERVAL}s)..."

# Unload previous version if present
if [[ -f "$LAUNCHDAEMON_PLIST" ]]; then
    launchctl unload "$LAUNCHDAEMON_PLIST" 2>/dev/null || true
fi

cat > "$LAUNCHDAEMON_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.wg0.heartbeat</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${HEARTBEAT_SCRIPT}</string>
    </array>
    <key>StartInterval</key>
    <integer>${HEARTBEAT_INTERVAL}</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/var/log/wg0-heartbeat.log</string>
    <key>StandardOutPath</key>
    <string>/var/log/wg0-heartbeat.log</string>
</dict>
</plist>
PLIST

if launchctl load "$LAUNCHDAEMON_PLIST" 2>/dev/null; then
    log "Heartbeat daemon installed (launchd, every ${HEARTBEAT_INTERVAL}s)."
    log "  Logs: /var/log/wg0-heartbeat.log"
    log "  Status: launchctl list | grep wg0"
else
    warn "launchctl load failed — falling back to background loop."
    while true; do
        sleep "$HEARTBEAT_INTERVAL"
        "$HEARTBEAT_SCRIPT" &>/dev/null || true
    done &
    disown
    log "Heartbeat loop started (PID $!)."
fi

# ── Install WireGuard watchdog — launchd daemon ───────────────────────────────
# wireguard-go exits on crash/reboot. This watchdog polls every 60s and brings
# the interface back up if it's gone, including cleaning any stale socket.
log "Installing launchd WireGuard watchdog daemon..."

if [[ -f "$WG_WATCHDOG_PLIST" ]]; then
    launchctl unload "$WG_WATCHDOG_PLIST" 2>/dev/null || true
fi

cat > "$WG_WATCHDOG_PLIST" <<WGPLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.wg0.wireguard</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>export PATH="${BREW_PREFIX}/bin:${BREW_PREFIX}/sbin:/usr/bin:/bin:/usr/sbin:/sbin"; WG_BIN=""; for p in "${BREW_PREFIX}/bin/wg" "/usr/local/bin/wg" "/usr/bin/wg"; do [[ -x "\$p" ]] &amp;&amp; { WG_BIN="\$p"; break; }; done; [[ -z "\$WG_BIN" ]] &amp;&amp; WG_BIN="wg"; WG_REAL=\$(cat /var/run/wireguard/${WG_IFACE}.name 2>/dev/null | tr -d '[:space:]'); [[ -z "\$WG_REAL" ]] &amp;&amp; WG_REAL=\$("\$WG_BIN" show interfaces 2&gt;/dev/null | awk '{print \$1}'); { [[ -n "\$WG_REAL" ]] &amp;&amp; "\$WG_BIN" show "\$WG_REAL" &gt;/dev/null 2&gt;&amp;1; } || { rm -f /var/run/wireguard/${WG_IFACE}.sock /var/run/wireguard/${WG_IFACE}.name; wg-quick up ${WG_CONF}; }</string>
    </array>
    <key>StartInterval</key>
    <integer>60</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/var/log/wg0-wireguard.log</string>
    <key>StandardOutPath</key>
    <string>/var/log/wg0-wireguard.log</string>
</dict>
</plist>
WGPLIST

if launchctl load "$WG_WATCHDOG_PLIST" 2>/dev/null; then
    log "WireGuard watchdog installed (launchd, checks every 60s, auto-restarts on crash/reboot)."
    log "  Logs: /var/log/wg0-wireguard.log"
else
    warn "WireGuard watchdog launchctl load failed — WireGuard will not auto-restart."
fi

# ── Install wg0 status CLI ────────────────────────────────────────────────────
REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo $USER)}"
if curl -fsSL "https://wg0.io/wg0-status.sh" -o /usr/local/bin/wg0 2>/dev/null; then
    chmod +x /usr/local/bin/wg0
    log "Installed: 'wg0 status' command"
fi

log ""
log "wg0 connector setup complete."
log "  WireGuard interface: ${WG_IFACE}"
log "  Node ID:             ${NODE_ID}"
log "  Config:              ${WG_CONF}"
log "  Keys:                ${KEY_DIR}/"
log ""
log "Check tunnel status anytime: wg0 status"
log ""
log "To unenroll this node later:"
log "  sudo $0 unenroll ${BRAIN_URL}"
