#!/usr/bin/env bash
# wg0 Connector
# Enrolls a node with the Brain and maintains WireGuard connectivity via heartbeat.
#
# Usage:
#   connector.sh enroll <TOKEN> <BRAIN_URL> [NODE_NAME] [OS_TYPE] [ROLE] [ADVERTISED_ROUTES_CSV]
#   connector.sh unenroll <BRAIN_URL>
#
#   # Legacy positional form (backward compatible — treated as "enroll"):
#   connector.sh <TOKEN> <BRAIN_URL> [NODE_NAME] [OS_TYPE] [ROLE] [ADVERTISED_ROUTES_CSV]
#
# Examples:
#   # Simple client node
#   ./connector.sh enroll eyJhbG... https://brain.example.com
#
#   # Host node advertising a LAN
#   ./connector.sh enroll eyJhbG... https://brain.example.com site-a-gw linux host 192.168.1.0/24
#
#   # Remove this node from the Brain and wipe all local WireGuard config
#   ./connector.sh unenroll https://brain.example.com
#
# Idempotent enroll — safe to re-run. Skips keygen/re-enrollment if already done.

set -euo pipefail

# ── Constants ─────────────────────────────────────────────────────────────────
WG_IFACE="wg0"
WG_CONF="/etc/wireguard/${WG_IFACE}.conf"
KEY_DIR="/etc/wireguard/wg0"
PRIV_KEY_FILE="${KEY_DIR}/private.key"
PUB_KEY_FILE="${KEY_DIR}/public.key"
NODE_ID_FILE="${KEY_DIR}/node_id"
DEVICE_SECRET_FILE="${KEY_DIR}/device_secret"
CONFIG_VERSION_FILE="${KEY_DIR}/config_version"
HEARTBEAT_INTERVAL=30
HEARTBEAT_SCRIPT="/usr/local/bin/wg0-heartbeat"

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "[wg0 $(date -u +%H:%M:%SZ)] $*"; }
die()  { log "ERROR: $*" >&2; exit 1; }
warn() { log "WARNING: $*" >&2; }

# ── Heartbeat template writer ─────────────────────────────────────────────────
# Used by both `enroll` and `update`. Reads global vars: HEARTBEAT_SCRIPT,
# BRAIN_URL, NODE_ID_FILE, WG_IFACE. Writes a fresh script that:
#   - Reports TX/RX bytes via heartbeat
#   - Applies peer map via `wg set`
#   - Adds matching system routes via `ip route replace` (idempotent)
write_heartbeat_script() {
    cat > "$HEARTBEAT_SCRIPT" <<HBSCRIPT
#!/usr/bin/env bash
# Auto-generated by wg0 connector. Do not edit manually.
NODE_ID="\$(cat ${NODE_ID_FILE})"
ROUTE_ALL_STATE="${KEY_DIR}/route_all_state"
SAME_LAN_STATE="${KEY_DIR}/same_lan_state"
OVERLAY_IP_FILE="${KEY_DIR}/overlay_ip"
# Device protocol v2: read the per-device secret (if this node was
# enrolled under v2). Empty string if the file doesn't exist — the
# brain's DeviceAuth extractor will accept the legacy path for pre-v2
# rows that have no stored hash yet.
DEVICE_SECRET="\$(cat ${DEVICE_SECRET_FILE} 2>/dev/null || true)"
PUBLIC_IP=\$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "")
ENDPOINT=""
[[ -n "\$PUBLIC_IP" ]] && ENDPOINT="\${PUBLIC_IP}:51820"

# If WireGuard is not up, skip — restart will be handled elsewhere.
ip link show ${WG_IFACE} >/dev/null 2>&1 || exit 0

# Collect TX/RX bytes (wg show transfer: <pubkey> <rx_bytes> <tx_bytes>)
TRANSFER=\$(wg show ${WG_IFACE} transfer 2>/dev/null)
TX_BYTES=\$(echo "\$TRANSFER" | awk '{sum += \$3} END {print sum+0}')
RX_BYTES=\$(echo "\$TRANSFER" | awk '{sum += \$2} END {print sum+0}')

# Per-peer observations from \`wg show <iface> dump\` — the brain merges
# these with the discover sidecar for the four-state presence model.
# First line is interface metadata (4 fields), subsequent lines are
# peers (8 fields: pubkey, psk, endpoint, allowed_ips, latest_handshake,
# rx, tx, keepalive). latest_handshake == 0 means "never," mapped to
# JSON null. jq -Rsc builds the JSON safely — no string concat.
PEERS_JSON=\$(wg show ${WG_IFACE} dump 2>/dev/null | tail -n +2 | awk -F'\\t' 'NF>=8 {
    printf "%s\\t%s\\t%s\\t%s\\n", \$1, \$5, \$6, \$7
}' | jq -Rsc '
    split("\\n") | map(select(length > 0) | split("\\t") | {
        public_key: .[0],
        last_handshake: (if .[1] == "0" then null else (.[1] | tonumber) end),
        rx_bytes: (.[2] | tonumber),
        tx_bytes: (.[3] | tonumber)
    })' 2>/dev/null)
[[ -z "\$PEERS_JSON" ]] && PEERS_JSON="[]"

# Report whether route-all is CURRENTLY active on this device. Read from
# the persisted state file that the previous heartbeat cycle wrote. The
# brain uses this to suppress the public-IP-equality same-LAN heuristic
# (which gives a false positive when route-all makes the client appear
# to egress from the host's public IP). "off" or missing file = false.
ROUTE_ALL_PREV_STATE=\$(cat "${KEY_DIR}/route_all_state" 2>/dev/null || echo "off")
if [[ "\$ROUTE_ALL_PREV_STATE" == on* ]]; then
    ROUTE_ALL_ACTIVE=true
else
    ROUTE_ALL_ACTIVE=false
fi

# BYO Exit kill-switch health probe (host nodes). If a previous
# heartbeat's BYO state machine brought up wg0-up via wg-quick, read
# its current handshake timestamp and report it to the brain so the
# dashboard can surface upstream failures. Linux uses the literal
# interface name — no utun indirection. Non-hosts and hosts without
# a currently-installed upstream send null so the brain doesn't
# overwrite anything.
UPSTREAM_HEALTH_JSON="null"
if ip link show wg0-up >/dev/null 2>&1; then
    WG_UP_LAST_HS=\$(wg show wg0-up latest-handshakes 2>/dev/null | awk '{ if (\$2 > 0) print \$2 }' | sort -nr | head -1)
    if [[ -n "\$WG_UP_LAST_HS" ]]; then
        UPSTREAM_HEALTH_JSON=\$(jq -cn --argjson lh "\$WG_UP_LAST_HS" '{interface_up: true, last_handshake: \$lh}')
    else
        UPSTREAM_HEALTH_JSON='{"interface_up": true, "last_handshake": null}'
    fi
fi

HB_BODY=\$(jq -cn \\
    --arg endpoint "\$ENDPOINT" \\
    --argjson tx_bytes \$TX_BYTES \\
    --argjson rx_bytes \$RX_BYTES \\
    --argjson peers "\$PEERS_JSON" \\
    --argjson route_all_active \$ROUTE_ALL_ACTIVE \\
    --argjson upstream_exit_health "\$UPSTREAM_HEALTH_JSON" \\
    '{endpoint:\$endpoint, tx_bytes:\$tx_bytes, rx_bytes:\$rx_bytes, peers:\$peers, route_all_active:\$route_all_active, upstream_exit_health:\$upstream_exit_health}')

CURL_ARGS=( -sf -X POST -H "Content-Type: application/json" )
[[ -n "\$DEVICE_SECRET" ]] && CURL_ARGS+=( -H "X-Device-Secret: \$DEVICE_SECRET" )
RESPONSE=\$(curl "\${CURL_ARGS[@]}" \\
    -d "\$HB_BODY" \\
    "${BRAIN_URL}/api/v1/nodes/\${NODE_ID}/heartbeat" 2>/dev/null) || exit 0

# ── Config drift detection (device protocol v2) ──────────────────────────
# Heartbeat response carries \`config_version\`. If the brain advertises a
# newer version than the one we have on disk, fetch the full wg_config,
# substitute the local private key into the PrivateKey placeholder, and
# \`wg syncconf\` the interface. This is how route/role changes initiated
# from the dashboard reach the device without a full re-enroll.
REMOTE_CONFIG_VERSION=\$(echo "\$RESPONSE" | jq -r '.config_version // 0')
LOCAL_CONFIG_VERSION=\$(cat "${CONFIG_VERSION_FILE}" 2>/dev/null || echo 0)
if [[ "\$REMOTE_CONFIG_VERSION" -gt "\$LOCAL_CONFIG_VERSION" ]]; then
    CONFIG_CURL_ARGS=( -sf )
    [[ -n "\$DEVICE_SECRET" ]] && CONFIG_CURL_ARGS+=( -H "X-Device-Secret: \$DEVICE_SECRET" )
    NEW_CFG_JSON=\$(curl "\${CONFIG_CURL_ARGS[@]}" \\
        "${BRAIN_URL}/api/v1/nodes/\${NODE_ID}/config" 2>/dev/null || true)
    if [[ -n "\$NEW_CFG_JSON" ]]; then
        NEW_WG_CONFIG=\$(echo "\$NEW_CFG_JSON" | jq -r '.wg_config // empty')
        if [[ -n "\$NEW_WG_CONFIG" && -f "${PRIV_KEY_FILE}" ]]; then
            PRIV_KEY_VALUE=\$(cat "${PRIV_KEY_FILE}")
            # Substitute the placeholder with the real private key,
            # write atomically, then syncconf the live interface.
            TMP_CONF=\$(mktemp)
            echo "\$NEW_WG_CONFIG" \\
                | sed "s|# PrivateKey = <CONNECTOR_FILLS_THIS_IN>|PrivateKey = \${PRIV_KEY_VALUE}|" \\
                > "\$TMP_CONF"
            chmod 600 "\$TMP_CONF"
            mv -f "\$TMP_CONF" "${WG_CONF}"
            # wg syncconf applies the diff in place — no interface
            # tear-down, no dropped sessions. wg-quick strip removes the
            # [Interface] directives wg doesn't understand.
            wg syncconf ${WG_IFACE} <(wg-quick strip "${WG_CONF}") 2>/dev/null || true
            echo "\$REMOTE_CONFIG_VERSION" > "${CONFIG_VERSION_FILE}"
            chmod 600 "${CONFIG_VERSION_FILE}"
        fi
    fi
fi

# Our own overlay /32 for use in same-LAN aliasing below.
OVERLAY_IP=\$(cat "\$OVERLAY_IP_FILE" 2>/dev/null | tr -d '[:space:]')

# Helper: find the current non-wg default gateway interface + gateway IP.
get_default() {
    ip route show default 2>/dev/null \
        | grep -v "dev ${WG_IFACE}" \
        | awk '/default/{print \$5, \$3; exit}'
}

# ── First pass: extract control-plane signals from peer list ──────────────
WANT_ROUTE_ALL=0
ROUTE_ALL_EP=""
ON_SAME_LAN=0
SAME_LAN_PEER_CIDRS=""  # space-separated, to be skipped in the per-peer route loop
while read -r _p; do
    _a=\$(echo "\$_p" | jq -r '.allowed_ips')
    _sl=\$(echo "\$_p" | jq -r '.on_same_lan // false')
    if [[ "\$_a" == *"0.0.0.0/0"* ]]; then
        WANT_ROUTE_ALL=1
        ROUTE_ALL_EP=\$(echo "\$_p" | jq -r '.endpoint // empty')
    fi
    if [[ "\$_sl" == "true" ]]; then
        ON_SAME_LAN=1
        for _c in \$(echo "\$_a" | tr ',' ' '); do
            SAME_LAN_PEER_CIDRS="\$SAME_LAN_PEER_CIDRS \$_c"
        done
    fi
done < <(echo "\$RESPONSE" | jq -c '.peers[]' 2>/dev/null)

# ── Route-all (full VPN) state machine ──────────────────────────────────────
ROUTE_ALL_PREV=\$(cat "\$ROUTE_ALL_STATE" 2>/dev/null || echo "off")

if [[ "\$WANT_ROUTE_ALL" = "1" && "\$ON_SAME_LAN" = "0" && -n "\$ROUTE_ALL_EP" ]]; then
    # Install exception route for the host's public endpoint via the
    # physical default gateway, then overlay the tunnel with two /1 routes
    # (more specific than the existing /0, so the endpoint exception wins).
    # We SKIP route-all install when on_same_lan is set: the tunnel can't
    # be trusted to carry traffic when we're on the host's LAN (hairpin
    # NAT would break the handshake).
    ENDPOINT_IP="\${ROUTE_ALL_EP%:*}"
    read -r _ DEFAULT_GW < <(get_default)
    if [[ -n "\$DEFAULT_GW" && -n "\$ENDPOINT_IP" ]]; then
        ip route replace "\${ENDPOINT_IP}/32" via "\$DEFAULT_GW" 2>/dev/null || true
    fi
    ip route replace 0.0.0.0/1   dev ${WG_IFACE} 2>/dev/null || true
    ip route replace 128.0.0.0/1 dev ${WG_IFACE} 2>/dev/null || true
    echo "on|\${ENDPOINT_IP}" > "\$ROUTE_ALL_STATE"
elif [[ "\$ROUTE_ALL_PREV" == on* ]]; then
    # Transition OUT of route-all: tear down /1 routes and the endpoint exception.
    ip route del 0.0.0.0/1   dev ${WG_IFACE} 2>/dev/null || true
    ip route del 128.0.0.0/1 dev ${WG_IFACE} 2>/dev/null || true
    PREV_EP="\${ROUTE_ALL_PREV#*|}"
    [[ -n "\$PREV_EP" ]] && ip route del "\${PREV_EP}/32" 2>/dev/null || true
    echo "off" > "\$ROUTE_ALL_STATE"
fi

# ── Same-LAN state machine ─────────────────────────────────────────────────
# When the brain flags the host peer as on_same_lan, we skip installing the
# tunnel routes for that peer (handled below in the per-peer loop) and
# optionally alias the overlay /32 on the physical default interface so
# other LAN devices can reach us at our overlay IP. State format:
#   "on|<iface>|<overlay-ip>" when aliased
#   "off" otherwise
SAME_LAN_PREV=\$(cat "\$SAME_LAN_STATE" 2>/dev/null || echo "off")

if [[ "\$ON_SAME_LAN" = "1" && -n "\$OVERLAY_IP" ]]; then
    read -r PHYS_IFACE _ < <(get_default)
    if [[ -n "\$PHYS_IFACE" && "\$SAME_LAN_PREV" != on* ]]; then
        # Transition IN: alias overlay IP on the physical interface so
        # LAN devices can ARP-resolve us at the overlay address.
        ip addr add "\${OVERLAY_IP}/32" dev "\$PHYS_IFACE" 2>/dev/null || true
        echo "on|\${PHYS_IFACE}|\${OVERLAY_IP}" > "\$SAME_LAN_STATE"
    fi
    # Also tear down any stale /32 or /24 kernel routes we previously
    # installed for the same-LAN peer — the physical LAN route handles it.
    for _c in \$SAME_LAN_PEER_CIDRS; do
        ip route del "\$_c" dev ${WG_IFACE} 2>/dev/null || true
    done
elif [[ "\$SAME_LAN_PREV" == on* ]]; then
    # Transition OUT: remove the alias from the physical interface. The
    # per-peer loop below will reinstall normal tunnel routes for the host.
    IFS='|' read -r _ PREV_IFACE PREV_OVERLAY <<< "\$SAME_LAN_PREV"
    if [[ -n "\$PREV_IFACE" && -n "\$PREV_OVERLAY" ]]; then
        ip addr del "\${PREV_OVERLAY}/32" dev "\$PREV_IFACE" 2>/dev/null || true
    fi
    echo "off" > "\$SAME_LAN_STATE"
fi

# ── BYO Exit: upstream WireGuard tunnel state machine (host nodes) ─────────
# The heartbeat response carries an optional \`upstream_exit\` object for host
# nodes that have an active exit assigned. Brain ships the full wg_config
# inline; we persist it as /etc/wireguard/wg0-up.conf and \`wg-quick up\` it.
#
# Desired state is encoded in UPSTREAM_STATE ("<id>" when active, "off"
# otherwise). Transitions:
#   off → on      : write conf, wg-quick up, install host-reachability
#                   policy route so our wg0 listener stays reachable
#   on  → on (same id): no-op (config may have been updated, refresh anyway)
#   on  → on (different id): tear down old, bring up new
#   on  → off     : wg-quick down, strip policy routing
UPSTREAM_STATE_FILE="${KEY_DIR}/upstream_exit_state"
UPSTREAM_CONF="/etc/wireguard/wg0-up.conf"

WANT_UPSTREAM_ID=\$(echo "\$RESPONSE" | jq -r '.upstream_exit.id // empty' 2>/dev/null)
WANT_UPSTREAM_CFG=\$(echo "\$RESPONSE" | jq -r '.upstream_exit.wg_config // empty' 2>/dev/null)
PREV_UPSTREAM_ID=\$(cat "\$UPSTREAM_STATE_FILE" 2>/dev/null || echo "off")

install_upstream_tunnel() {
    local cfg="\$1"

    # Write the config to disk with tight perms — it contains a private key.
    umask 077
    echo "\$cfg" > "\$UPSTREAM_CONF"

    # Host-reachability policy route: when the upstream tunnel becomes the
    # default route, our wg0 UDP listener's replies would go out via the
    # upstream (wrong interface, wrong source IP, black-holed). Mark packets
    # sourced from UDP 51820 and steer them via the ORIGINAL physical
    # gateway before the upstream takes over.
    local orig_iface orig_gw
    read -r orig_iface orig_gw < <(get_default)
    if [[ -n "\$orig_iface" && -n "\$orig_gw" ]]; then
        # Secondary routing table 51820: default via original ISP gateway
        grep -q '^51820 wg0-listener' /etc/iproute2/rt_tables 2>/dev/null \
            || echo "51820 wg0-listener" >> /etc/iproute2/rt_tables 2>/dev/null || true
        ip route replace default via "\$orig_gw" dev "\$orig_iface" table 51820 2>/dev/null || true
        ip rule del fwmark 0x100 lookup 51820 2>/dev/null || true
        ip rule add fwmark 0x100 lookup 51820 2>/dev/null || true
        # Tag packets sourced from UDP 51820 on output
        iptables -t mangle -C OUTPUT -p udp --sport 51820 -j MARK --set-mark 0x100 2>/dev/null \
            || iptables -t mangle -A OUTPUT -p udp --sport 51820 -j MARK --set-mark 0x100 2>/dev/null || true
    fi

    # Bring the upstream tunnel up (wg-quick handles the default route
    # replacement for us when AllowedIPs includes 0.0.0.0/0)
    wg-quick up "\$UPSTREAM_CONF" 2>/dev/null || wg-quick up wg0-up 2>/dev/null || true
}

teardown_upstream_tunnel() {
    wg-quick down wg0-up 2>/dev/null \
        || wg-quick down "\$UPSTREAM_CONF" 2>/dev/null || true
    # Remove policy rules (best-effort)
    ip rule del fwmark 0x100 lookup 51820 2>/dev/null || true
    iptables -t mangle -D OUTPUT -p udp --sport 51820 -j MARK --set-mark 0x100 2>/dev/null || true
    rm -f "\$UPSTREAM_CONF"
}

if [[ -n "\$WANT_UPSTREAM_ID" && -n "\$WANT_UPSTREAM_CFG" ]]; then
    if [[ "\$PREV_UPSTREAM_ID" != "\$WANT_UPSTREAM_ID" ]]; then
        # Transition: either off→on or on→different id. Tear down any
        # existing upstream before installing the new one.
        [[ "\$PREV_UPSTREAM_ID" != "off" ]] && teardown_upstream_tunnel
        install_upstream_tunnel "\$WANT_UPSTREAM_CFG"
        echo "\$WANT_UPSTREAM_ID" > "\$UPSTREAM_STATE_FILE"
    fi
elif [[ "\$PREV_UPSTREAM_ID" != "off" ]]; then
    # Transition on → off
    teardown_upstream_tunnel
    echo "off" > "\$UPSTREAM_STATE_FILE"
fi

# ── Apply peer map updates ──────────────────────────────────────────────────
# wg set updates WireGuard's crypto-key routing table. System routes are
# added for each allowed_ips CIDR so packets actually reach the tunnel.
# 0.0.0.0/0 is handled above via the split-tunnel state machine — skip it
# in the per-peer loop so we don't clobber the /1 pair with a /0 replace.
# Peers flagged on_same_lan also skip route installation — LAN handles it.
echo "\$RESPONSE" | jq -c '.peers[]' 2>/dev/null | while read -r peer; do
    PUBKEY=\$(echo "\$peer" | jq -r '.public_key')
    ALLOWED=\$(echo "\$peer" | jq -r '.allowed_ips')
    EP=\$(echo "\$peer" | jq -r '.endpoint // empty')
    PEER_SAME_LAN=\$(echo "\$peer" | jq -r '.on_same_lan // false')
    if [[ -n "\$EP" ]]; then
        wg set ${WG_IFACE} peer "\$PUBKEY" allowed-ips "\$ALLOWED" endpoint "\$EP" persistent-keepalive 25
    else
        wg set ${WG_IFACE} peer "\$PUBKEY" allowed-ips "\$ALLOWED" persistent-keepalive 25
    fi
    [[ "\$PEER_SAME_LAN" == "true" ]] && continue
    echo "\$ALLOWED" | tr ',' '\\n' | tr -d ' ' | while read -r cidr; do
        [[ -z "\$cidr" || "\$cidr" == "0.0.0.0/0" ]] && continue
        ip route replace "\$cidr" dev ${WG_IFACE} 2>/dev/null || true
    done
done
HBSCRIPT
    chmod +x "$HEARTBEAT_SCRIPT"
}

# ── Subcommand dispatch ───────────────────────────────────────────────────────
SUBCMD="${1:-}"

# Detect legacy positional form: first arg looks like a token (not a keyword)
if [[ "$SUBCMD" != "enroll" && "$SUBCMD" != "unenroll" && "$SUBCMD" != "update" && "$SUBCMD" != "rotate-secret" ]]; then
    # Treat entire invocation as "enroll TOKEN BRAIN_URL ..."
    SUBCMD="enroll"
    TOKEN="${1:-}"
    BRAIN_URL="${2:-}"
    NODE_NAME="${3:-$(hostname)}"
    OS_TYPE="${4:-linux}"
    ROLE="${5:-client}"
    ADVERTISED_ROUTES_CSV="${6:-}"
else
    shift  # consume subcommand token
    if [[ "$SUBCMD" == "unenroll" ]]; then
        BRAIN_URL="${1:-}"
        # Auto-detect brain URL from stored file if not given
        if [[ -z "$BRAIN_URL" ]]; then
            for d in /etc/wireguard/wg0 /etc/wireguard/abslink; do
                [[ -f "$d/brain_url" ]] && BRAIN_URL=$(cat "$d/brain_url") && break
            done
        fi
        [[ -n "$BRAIN_URL" ]] || { echo "Usage: $0 unenroll [BRAIN_URL]"; exit 1; }
    elif [[ "$SUBCMD" == "update" ]]; then
        BRAIN_URL="${1:-}"
        [[ -n "$BRAIN_URL" ]] || { echo "Usage: $0 update <NEW_BRAIN_URL>"; exit 1; }
    elif [[ "$SUBCMD" == "rotate-secret" ]]; then
        BRAIN_URL="${1:-}"
        if [[ -z "$BRAIN_URL" ]]; then
            for d in /etc/wireguard/wg0 /etc/wireguard/abslink; do
                [[ -f "$d/brain_url" ]] && BRAIN_URL=$(cat "$d/brain_url") && break
            done
        fi
        [[ -n "$BRAIN_URL" ]] || { echo "Usage: $0 rotate-secret [BRAIN_URL]"; exit 1; }
    else
        # enroll subcommand
        TOKEN="${1:-}"
        BRAIN_URL="${2:-}"
        NODE_NAME="${3:-$(hostname)}"
        OS_TYPE="${4:-linux}"
        ROLE="${5:-client}"
        ADVERTISED_ROUTES_CSV="${6:-}"
    fi
fi

# ── ROTATE-SECRET ─────────────────────────────────────────────────────────────
# Device protocol v2: generate a new per-device secret, atomically overwrite
# the local file. Uses the current secret to authenticate the POST — for
# pre-v2 rows that don't have a secret file, the brain's grace-path accepts
# the unauthenticated call, generates the first hash, and transitions the
# row to strict auth going forward.
if [[ "$SUBCMD" == "rotate-secret" ]]; then
    BRAIN_URL="${BRAIN_URL%/}"
    [[ -f "$NODE_ID_FILE" ]] || die "No node_id found. This system does not appear to be enrolled."
    NODE_ID=$(cat "$NODE_ID_FILE")
    log "Rotating device secret for node ${NODE_ID} at ${BRAIN_URL}"

    CUR_SECRET=$(cat "$DEVICE_SECRET_FILE" 2>/dev/null || true)
    ROTATE_ARGS=( -sf -X POST -H "Content-Type: application/json" )
    [[ -n "$CUR_SECRET" ]] && ROTATE_ARGS+=( -H "X-Device-Secret: $CUR_SECRET" )
    RESP=$(curl "${ROTATE_ARGS[@]}" "${BRAIN_URL}/api/v1/nodes/${NODE_ID}/rotate-secret" -d '{}') \
        || die "rotate-secret request failed — brain unreachable or current secret rejected."

    NEW_SECRET=$(echo "$RESP" | jq -r '.device_secret // empty')
    [[ -n "$NEW_SECRET" ]] || die "Brain returned no device_secret in rotate response: $RESP"

    # Atomic overwrite so a crash mid-rotate doesn't brick the node.
    TMP_SECRET=$(mktemp -p "$KEY_DIR" .device_secret.XXXXXX)
    printf '%s' "$NEW_SECRET" > "$TMP_SECRET"
    chmod 600 "$TMP_SECRET"
    mv -f "$TMP_SECRET" "$DEVICE_SECRET_FILE"

    log "Device secret rotated successfully. Future heartbeats will use the new secret."
    exit 0
fi

# ── UPDATE ────────────────────────────────────────────────────────────────────
if [[ "$SUBCMD" == "update" ]]; then
    BRAIN_URL="${BRAIN_URL%/}"
    log "wg0 update — migrating to brain at ${BRAIN_URL}"

    # Detect current key dir (legacy or new)
    if [[ -d /etc/wireguard/abslink && ! -d /etc/wireguard/wg0 ]]; then
        log "Migrating key directory: /etc/wireguard/abslink → ${KEY_DIR}"
        mv /etc/wireguard/abslink "$KEY_DIR"
    fi

    NODE_ID_FILE="${KEY_DIR}/node_id"
    [[ -f "$NODE_ID_FILE" ]] || die "No node_id found. This system does not appear to be enrolled."
    NODE_ID=$(cat "$NODE_ID_FILE")
    log "Node ID: ${NODE_ID}"

    # Store brain URL
    echo "$BRAIN_URL" > "${KEY_DIR}/brain_url"
    chmod 600 "${KEY_DIR}/brain_url"

    # Remove legacy heartbeat script (we'll write a fresh one below)
    rm -f /usr/local/bin/abslink-heartbeat

    # Rewrite heartbeat script from current template — handles brain URL,
    # route logic, TX/RX reporting, all in one shot. No fragile sed patches.
    write_heartbeat_script
    log "Rewrote heartbeat script with latest template (brain=${BRAIN_URL})"

    # Migrate systemd unit names if needed
    if [[ -f /etc/systemd/system/abslink-heartbeat.timer ]]; then
        log "Migrating systemd units: abslink-heartbeat → wg0-heartbeat"
        systemctl disable --now abslink-heartbeat.timer 2>/dev/null || true
        # Rewrite with new name
        sed 's|abslink-heartbeat|wg0-heartbeat|g; s|abslink|wg0|g' \
            /etc/systemd/system/abslink-heartbeat.service > /etc/systemd/system/wg0-heartbeat.service
        sed 's|abslink-heartbeat|wg0-heartbeat|g; s|abslink|wg0|g' \
            /etc/systemd/system/abslink-heartbeat.timer > /etc/systemd/system/wg0-heartbeat.timer
        rm -f /etc/systemd/system/abslink-heartbeat.service /etc/systemd/system/abslink-heartbeat.timer
        systemctl daemon-reload
        systemctl enable --now wg0-heartbeat.timer
        log "Systemd units migrated and started"
    elif [[ -f /etc/systemd/system/wg0-heartbeat.timer ]]; then
        systemctl restart wg0-heartbeat.timer 2>/dev/null || true
        log "Heartbeat timer restarted"
    fi

    # Install/update wg0 CLI
    if curl -fsSL "https://wg0.io/wg0-status.sh" -o /usr/local/bin/wg0 2>/dev/null; then
        chmod +x /usr/local/bin/wg0
        log "Updated wg0 CLI tool"
    fi
    rm -f /usr/local/bin/abslink 2>/dev/null || true

    # Test heartbeat
    log "Running heartbeat to verify connectivity..."
    if bash "$HEARTBEAT_SCRIPT" 2>/dev/null; then
        log "Heartbeat succeeded — connected to ${BRAIN_URL}"
    else
        warn "Heartbeat failed — check that ${BRAIN_URL} is reachable"
    fi

    log ""
    log "Update complete."
    log "  Brain URL:  ${BRAIN_URL}"
    log "  Node ID:    ${NODE_ID}"
    log ""
    log "Run 'wg0 status' to verify tunnel health."
    exit 0
fi

# ── UNENROLL ──────────────────────────────────────────────────────────────────
if [[ "$SUBCMD" == "unenroll" ]]; then
    BRAIN_URL="${BRAIN_URL%/}"

    log "Starting unenroll from Brain at ${BRAIN_URL} ..."

    # 1. Read node_id — die if not enrolled
    if [[ ! -f "$NODE_ID_FILE" ]]; then
        die "No node_id found at ${NODE_ID_FILE}. This system does not appear to be enrolled."
    fi
    NODE_ID=$(cat "$NODE_ID_FILE")
    log "Node ID: ${NODE_ID}"

    # 2. Tell the Brain to forget this node (warn and continue if Brain unreachable).
    # Send X-Device-Secret if this node was enrolled under protocol v2;
    # older enrollments don't have a secret file and the brain's extractor
    # accepts the request without it (grace-period backward compat).
    log "Notifying Brain to remove node..."
    DEVICE_SECRET=$(cat "$DEVICE_SECRET_FILE" 2>/dev/null || true)
    UNENROLL_ARGS=( -sf -X DELETE )
    [[ -n "$DEVICE_SECRET" ]] && UNENROLL_ARGS+=( -H "X-Device-Secret: $DEVICE_SECRET" )
    if curl "${UNENROLL_ARGS[@]}" "${BRAIN_URL}/api/v1/nodes/${NODE_ID}/self" >/dev/null 2>&1; then
        log "Brain confirmed node removal."
    else
        log "WARNING: Brain request failed (Brain may be unreachable). Continuing local cleanup."
    fi

    # 3. Bring down WireGuard interface
    if ip link show "$WG_IFACE" >/dev/null 2>&1; then
        log "Bringing down WireGuard interface ${WG_IFACE}..."
        wg-quick down "$WG_CONF" 2>/dev/null || wg-quick down "$WG_IFACE" 2>/dev/null || true
    else
        log "WireGuard interface ${WG_IFACE} is already down."
    fi

    # 4. Stop and disable systemd units
    if command -v systemctl >/dev/null 2>&1; then
        systemctl disable --now wg0-heartbeat.timer  2>/dev/null || true
        systemctl disable --now wg0-heartbeat.service 2>/dev/null || true
    fi

    # 5. Remove systemd unit files and reload daemon
    if [[ -f /etc/systemd/system/wg0-heartbeat.timer || -f /etc/systemd/system/wg0-heartbeat.service ]]; then
        rm -f /etc/systemd/system/wg0-heartbeat.timer
        rm -f /etc/systemd/system/wg0-heartbeat.service
        systemctl daemon-reload 2>/dev/null || true
        log "Removed systemd heartbeat units."
    fi

    # 6. Remove heartbeat script
    rm -f "$HEARTBEAT_SCRIPT"
    log "Removed heartbeat script."

    # 7. Remove WireGuard config
    rm -f "$WG_CONF"
    log "Removed WireGuard config ${WG_CONF}."

    # 8. Remove keys and node_id
    rm -rf "$KEY_DIR"
    log "Removed key directory ${KEY_DIR}."

    log "Unenroll complete. This node has been removed from wg0."
    exit 0
fi

# ── ENROLL ────────────────────────────────────────────────────────────────────
if [[ -z "${TOKEN:-}" || -z "${BRAIN_URL:-}" ]]; then
    echo "Usage:"
    echo "  $0 enroll <TOKEN> <BRAIN_URL> [NODE_NAME] [OS_TYPE] [ROLE] [ADVERTISED_ROUTES_CSV]"
    echo "  $0 unenroll <BRAIN_URL>"
    exit 1
fi

BRAIN_URL="${BRAIN_URL%/}"  # strip trailing slash

# ── Dependency check ──────────────────────────────────────────────────────────
for cmd in wg wg-quick curl jq; do
    command -v "$cmd" >/dev/null 2>&1 || die "Required command '$cmd' not found. Install it and retry."
done

# ── Directory setup ───────────────────────────────────────────────────────────
mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"

# ── Key generation ────────────────────────────────────────────────────────────
if [[ ! -f "$PRIV_KEY_FILE" ]]; then
    log "Generating WireGuard keypair..."
    wg genkey | tee "$PRIV_KEY_FILE" | wg pubkey > "$PUB_KEY_FILE"
    chmod 600 "$PRIV_KEY_FILE"
fi
PRIV_KEY=$(cat "$PRIV_KEY_FILE")
PUB_KEY=$(cat "$PUB_KEY_FILE")
log "Public key: $PUB_KEY"

# ── Detect public endpoint ────────────────────────────────────────────────────
PUBLIC_IP=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "")
ENDPOINT=""
[[ -n "$PUBLIC_IP" ]] && ENDPOINT="${PUBLIC_IP}:51820"

# ── Enrollment ────────────────────────────────────────────────────────────────
if [[ ! -f "$NODE_ID_FILE" ]]; then
    log "Enrolling node '${NODE_NAME}' (role=${ROLE}) with Brain at ${BRAIN_URL} ..."

    # Build JSON payload
    if [[ -n "$ADVERTISED_ROUTES_CSV" ]]; then
        # Convert "192.168.1.0/24,10.0.0.0/8" → ["192.168.1.0/24","10.0.0.0/8"]
        ROUTES_JSON=$(echo "$ADVERTISED_ROUTES_CSV" | python3 -c "
import sys, json
routes = [r.strip() for r in sys.stdin.read().strip().split(',') if r.strip()]
print(json.dumps(routes))
")
    else
        ROUTES_JSON="[]"
    fi

    PAYLOAD=$(cat <<EOF
{
    "token": "${TOKEN}",
    "public_key": "${PUB_KEY}",
    "node_name": "${NODE_NAME}",
    "os_type": "${OS_TYPE}",
    "role": "${ROLE}",
    "advertised_routes": ${ROUTES_JSON},
    "endpoint": "${ENDPOINT}"
}
EOF
)

    ENROLL_RESPONSE=$(curl -sf -X POST \
        -H "Content-Type: application/json" \
        -d "$PAYLOAD" \
        "${BRAIN_URL}/api/v1/enroll/register") \
        || die "Enrollment failed. Check TOKEN and BRAIN_URL. Brain returned an error."

    NODE_ID=$(echo "$ENROLL_RESPONSE" | jq -r '.node_id')
    OVERLAY_IP=$(echo "$ENROLL_RESPONSE" | jq -r '.overlay_ip')
    WG_CONFIG=$(echo "$ENROLL_RESPONSE" | jq -r '.wg_config')
    # Device protocol v2 secret — returned ONCE in the enrollment
    # response. Store it at 0600 next to the private key; the heartbeat
    # script reads it and sends it as X-Device-Secret on every request.
    DEVICE_SECRET=$(echo "$ENROLL_RESPONSE" | jq -r '.device_secret // empty')

    echo "$NODE_ID" > "$NODE_ID_FILE"
    chmod 600 "$NODE_ID_FILE"
    echo "$BRAIN_URL" > "${KEY_DIR}/brain_url"
    chmod 600 "${KEY_DIR}/brain_url"
    if [[ -n "$DEVICE_SECRET" ]]; then
        printf '%s' "$DEVICE_SECRET" > "$DEVICE_SECRET_FILE"
        chmod 600 "$DEVICE_SECRET_FILE"
    fi
    # Bare overlay IP (no /prefix) — used by the heartbeat's same-LAN
    # state machine to alias the overlay /32 on the physical interface.
    echo "${OVERLAY_IP%/*}" > "${KEY_DIR}/overlay_ip"
    chmod 600 "${KEY_DIR}/overlay_ip"

    # Write wg conf — substitute private key placeholder
    echo "$WG_CONFIG" \
        | sed "s|# PrivateKey = <CONNECTOR_FILLS_THIS_IN>|PrivateKey = ${PRIV_KEY}|" \
        > "$WG_CONF"
    chmod 600 "$WG_CONF"

    log "Enrolled! Overlay/Assigned IP: ${OVERLAY_IP} | Node ID: ${NODE_ID}"
fi

NODE_ID=$(cat "$NODE_ID_FILE")

# ── Bring up WireGuard ────────────────────────────────────────────────────────
if ! ip link show "$WG_IFACE" >/dev/null 2>&1; then
    log "Bringing up WireGuard interface ${WG_IFACE}..."
    wg-quick up "$WG_CONF" || die "Failed to bring up WireGuard. Check /var/log/syslog."
fi
log "Interface ${WG_IFACE} is up."

# ── Heartbeat script ──────────────────────────────────────────────────────────
write_heartbeat_script

# ── Install heartbeat — systemd or fallback loop ──────────────────────────────
if command -v systemctl >/dev/null 2>&1 && [[ -d /etc/systemd/system ]]; then
    cat > /etc/systemd/system/wg0-heartbeat.service <<EOF
[Unit]
Description=wg0 Heartbeat

[Service]
Type=oneshot
ExecStart=${HEARTBEAT_SCRIPT}
EOF

    cat > /etc/systemd/system/wg0-heartbeat.timer <<EOF
[Unit]
Description=wg0 Heartbeat Timer
After=network-online.target

[Timer]
OnBootSec=10s
OnUnitActiveSec=${HEARTBEAT_INTERVAL}s

[Install]
WantedBy=timers.target
EOF

    systemctl daemon-reload
    systemctl enable --now wg0-heartbeat.timer
    log "Heartbeat timer installed (systemd, every ${HEARTBEAT_INTERVAL}s)."

else
    # Non-systemd fallback: background loop (OpenWRT, proprietary channel banks, etc.)
    log "systemd not found — starting background heartbeat loop (every ${HEARTBEAT_INTERVAL}s)..."
    while true; do
        sleep "$HEARTBEAT_INTERVAL"
        "$HEARTBEAT_SCRIPT" &>/dev/null || true
    done &
    disown
    log "Heartbeat loop started (PID $!)."
fi

# ── Install wg0 status CLI ────────────────────────────────────────────────
if curl -fsSL "${BRAIN_URL%/api*}/../wg0-status.sh" -o /usr/local/bin/wg0 2>/dev/null \
   || curl -fsSL "https://wg0.io/wg0-status.sh" -o /usr/local/bin/wg0 2>/dev/null; then
    chmod +x /usr/local/bin/wg0
    log "Installed: 'wg0 status' command"
fi

log ""
log "wg0 connector setup complete."
log "  WireGuard interface: ${WG_IFACE}"
log "  Node ID:             ${NODE_ID}"
log "  Config:              ${WG_CONF}"
log ""
log "Check tunnel status anytime: wg0 status"
