#!/usr/bin/env bash
# wg0 Connector — macOS
#
# Enrolls a macOS node with the Brain and maintains WireGuard connectivity.
# Automatically installs Homebrew dependencies (wireguard-tools, jq) if missing.
# Works on Apple Silicon (arm64) and Intel (x86_64). Requires macOS 11+.
#
# Usage:
#   sudo ./connector-macos.sh enroll <TOKEN> <BRAIN_URL> [NODE_NAME] [ROLE]
#   sudo ./connector-macos.sh unenroll <BRAIN_URL>
#
# Examples:
#   # Host node (macOS machine on your LAN — used for native LAN mode)
#   sudo ./connector-macos.sh enroll eyJhbG... https://brain.example.com $(hostname) host
#
#   # Client node (remote device that connects through the network)
#   sudo ./connector-macos.sh enroll eyJhbG... https://brain.example.com my-macbook client
#
#   # Remove this node from the Brain and wipe all local WireGuard config
#   sudo ./connector-macos.sh unenroll https://brain.example.com
#
# Idempotent enroll — safe to re-run.

set -euo pipefail

# ── Constants ─────────────────────────────────────────────────────────────────
WG_IFACE="wg0"
WG_CONF="/etc/wireguard/${WG_IFACE}.conf"
KEY_DIR="/etc/wireguard/wg0"
PRIV_KEY_FILE="${KEY_DIR}/private.key"
PUB_KEY_FILE="${KEY_DIR}/public.key"
NODE_ID_FILE="${KEY_DIR}/node_id"
DEVICE_SECRET_FILE="${KEY_DIR}/device_secret"
CONFIG_VERSION_FILE="${KEY_DIR}/config_version"
HEARTBEAT_INTERVAL=30
HEARTBEAT_SCRIPT="/usr/local/bin/wg0-heartbeat"
POSTUP_SCRIPT="/usr/local/bin/wg0-postup"
PREDOWN_SCRIPT="/usr/local/bin/wg0-predown"
LAUNCHDAEMON_PLIST="/Library/LaunchDaemons/io.wg0.heartbeat.plist"
WG_WATCHDOG_PLIST="/Library/LaunchDaemons/io.wg0.wireguard.plist"

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "[wg0 $(date -u +%H:%M:%SZ)] $*"; }
die()  { log "ERROR: $*" >&2; exit 1; }
warn() { log "WARNING: $*" >&2; }

# ── Must run as root ──────────────────────────────────────────────────────────
[[ "$EUID" -eq 0 ]] || die "This script must be run with sudo."

# ── Architecture detection + Homebrew path ────────────────────────────────────
ARCH=$(uname -m)
if [[ "$ARCH" == "arm64" ]]; then
    BREW_PREFIX="/opt/homebrew"
else
    BREW_PREFIX="/usr/local"
fi
BREW="${BREW_PREFIX}/bin/brew"

# ── Heartbeat template writer ─────────────────────────────────────────────────
# Used by both `enroll` and `update`. Reads global vars: HEARTBEAT_SCRIPT,
# BRAIN_URL, NODE_ID_FILE, WG_IFACE, BREW_PREFIX. Writes a fresh script that:
#   - Resolves the real utun interface (macOS userspace WireGuard quirk)
#   - Reports TX/RX bytes via heartbeat
#   - Applies peer map via `wg set`
#   - Adds matching system routes (delete-then-add for idempotency across
#     interface renumbering when wireguard-go restarts)
write_heartbeat_script() {
    cat > "$HEARTBEAT_SCRIPT" <<HBSCRIPT
#!/usr/bin/env bash
# Auto-generated by wg0 connector (macOS). Do not edit manually.
export PATH="${BREW_PREFIX}/bin:${BREW_PREFIX}/sbin:\$PATH"
NODE_ID="\$(cat ${NODE_ID_FILE})"
ROUTE_ALL_STATE="${KEY_DIR}/route_all_state"
SAME_LAN_STATE="${KEY_DIR}/same_lan_state"
OVERLAY_IP_FILE="${KEY_DIR}/overlay_ip"

# macOS userspace WireGuard maps the logical name (wg0) to a utun device.
# Every wg/route call must use the real utun name, not the logical alias.
WG_REAL=\$(cat /var/run/wireguard/${WG_IFACE}.name 2>/dev/null | tr -d '[:space:]')
[[ -z "\$WG_REAL" ]] && WG_REAL="${WG_IFACE}"

# If wireguard-go is not running, skip — the watchdog will restart it.
wg show "\$WG_REAL" >/dev/null 2>&1 || exit 0

# Device protocol v2 secret (see docs/DEVICE_PROTOCOL.md). Empty string
# for nodes enrolled before v2 — the brain's grace-period path accepts
# the legacy "node_id is the credential" behavior for those rows.
DEVICE_SECRET=\$(cat "${DEVICE_SECRET_FILE}" 2>/dev/null || true)

PUBLIC_IP=\$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "")
ENDPOINT=""
[[ -n "\$PUBLIC_IP" ]] && ENDPOINT="\${PUBLIC_IP}:51820"

# Collect TX/RX bytes from WireGuard (wg show transfer: <pubkey> <rx> <tx>)
TRANSFER=\$(wg show "\$WG_REAL" transfer 2>/dev/null)
TX_BYTES=\$(echo "\$TRANSFER" | awk '{sum += \$3} END {print sum+0}')
RX_BYTES=\$(echo "\$TRANSFER" | awk '{sum += \$2} END {print sum+0}')

# Per-peer observations from \`wg show <iface> dump\` — the brain merges
# these with the discover sidecar for the four-state presence model.
# Dump format: the first line is the interface (4 fields), subsequent
# lines are peers (8 fields: pubkey, psk, endpoint, allowed_ips,
# latest_handshake, rx, tx, keepalive). latest_handshake == 0 means
# "never," which we map to JSON null so the brain's Option<i64> is
# honest about missing data. jq -Rsc builds the JSON safely — no
# string concat, pubkeys are untrusted.
PEERS_JSON=\$(wg show "\$WG_REAL" dump 2>/dev/null | tail -n +2 | awk -F'\\t' 'NF>=8 {
    printf "%s\\t%s\\t%s\\t%s\\n", \$1, \$5, \$6, \$7
}' | jq -Rsc '
    split("\\n") | map(select(length > 0) | split("\\t") | {
        public_key: .[0],
        last_handshake: (if .[1] == "0" then null else (.[1] | tonumber) end),
        rx_bytes: (.[2] | tonumber),
        tx_bytes: (.[3] | tonumber)
    })' 2>/dev/null)
[[ -z "\$PEERS_JSON" ]] && PEERS_JSON="[]"

# Build the POST body with jq so observed peer data is always valid JSON
# (avoids shell-quoting foot-guns when pubkeys contain \`/\` or \`+\`).
# Report whether route-all is currently active. Read from the state
# file the previous heartbeat cycle wrote. Used by the brain to
# suppress the public-IP-equality same-LAN heuristic (which gives a
# false positive when route-all egresses the client through the host).
ROUTE_ALL_PREV_STATE=\$(cat "${KEY_DIR}/route_all_state" 2>/dev/null || echo "off")
if [[ "\$ROUTE_ALL_PREV_STATE" == on* ]]; then
    ROUTE_ALL_ACTIVE=true
else
    ROUTE_ALL_ACTIVE=false
fi

# BYO Exit kill-switch health probe. If a previous heartbeat's BYO
# state machine brought up wg0-up via wg-quick, we can read its
# current handshake timestamp via \`wg show\` and report it to the
# brain so the dashboard can surface upstream failures. macOS maps
# the logical name "wg0-up" to a utun device via
# /var/run/wireguard/wg0-up.name (same pattern as wg0). Non-hosts
# and hosts without a currently-installed upstream send null so
# the brain doesn't overwrite anything.
UPSTREAM_HEALTH_JSON="null"
if [[ -f "/var/run/wireguard/wg0-up.name" ]]; then
    WG_UP_REAL=\$(cat /var/run/wireguard/wg0-up.name 2>/dev/null | tr -d '[:space:]')
    if [[ -n "\$WG_UP_REAL" ]] && wg show "\$WG_UP_REAL" >/dev/null 2>&1; then
        # latest-handshakes output is "<pubkey>\\t<unix_seconds>"
        # per peer. 0 means "never handshook." Take the max across
        # all peers (there's usually one — the provider's endpoint).
        WG_UP_LAST_HS=\$(wg show "\$WG_UP_REAL" latest-handshakes 2>/dev/null | awk '{ if (\$2 > 0) print \$2 }' | sort -nr | head -1)
        if [[ -n "\$WG_UP_LAST_HS" ]]; then
            UPSTREAM_HEALTH_JSON=\$(jq -cn --argjson lh "\$WG_UP_LAST_HS" '{interface_up: true, last_handshake: \$lh}')
        else
            UPSTREAM_HEALTH_JSON='{"interface_up": true, "last_handshake": null}'
        fi
    else
        # .name file exists but the utun device is gone — typically
        # after wg-quick up succeeded but wireguard-go crashed.
        UPSTREAM_HEALTH_JSON='{"interface_up": false, "last_handshake": null}'
    fi
fi

HB_BODY=\$(jq -cn \\
    --arg endpoint "\$ENDPOINT" \\
    --argjson tx_bytes \$TX_BYTES \\
    --argjson rx_bytes \$RX_BYTES \\
    --argjson peers "\$PEERS_JSON" \\
    --argjson route_all_active \$ROUTE_ALL_ACTIVE \\
    --argjson upstream_exit_health "\$UPSTREAM_HEALTH_JSON" \\
    '{endpoint:\$endpoint, tx_bytes:\$tx_bytes, rx_bytes:\$rx_bytes, peers:\$peers, route_all_active:\$route_all_active, upstream_exit_health:\$upstream_exit_health}')

CURL_ARGS=( -sf -X POST -H "Content-Type: application/json" )
[[ -n "\$DEVICE_SECRET" ]] && CURL_ARGS+=( -H "X-Device-Secret: \$DEVICE_SECRET" )
RESPONSE=\$(curl "\${CURL_ARGS[@]}" \\
    -d "\$HB_BODY" \\
    "${BRAIN_URL}/api/v1/nodes/\${NODE_ID}/heartbeat" 2>/dev/null) || exit 0

# ── Config drift detection (device protocol v2) ──────────────────────────
# Heartbeat response carries \`config_version\`. If the brain advertises a
# newer version than the one we have on disk, fetch the full wg_config,
# substitute the local private key, and \`wg syncconf\` the utun interface.
REMOTE_CONFIG_VERSION=\$(echo "\$RESPONSE" | jq -r '.config_version // 0')
LOCAL_CONFIG_VERSION=\$(cat "${CONFIG_VERSION_FILE}" 2>/dev/null || echo 0)
if [[ "\$REMOTE_CONFIG_VERSION" -gt "\$LOCAL_CONFIG_VERSION" ]]; then
    CONFIG_CURL_ARGS=( -sf )
    [[ -n "\$DEVICE_SECRET" ]] && CONFIG_CURL_ARGS+=( -H "X-Device-Secret: \$DEVICE_SECRET" )
    NEW_CFG_JSON=\$(curl "\${CONFIG_CURL_ARGS[@]}" \\
        "${BRAIN_URL}/api/v1/nodes/\${NODE_ID}/config" 2>/dev/null || true)
    if [[ -n "\$NEW_CFG_JSON" ]]; then
        NEW_WG_CONFIG=\$(echo "\$NEW_CFG_JSON" | jq -r '.wg_config // empty')
        if [[ -n "\$NEW_WG_CONFIG" && -f "${PRIV_KEY_FILE}" ]]; then
            PRIV_KEY_VALUE=\$(cat "${PRIV_KEY_FILE}")
            TMP_CONF=\$(mktemp)
            echo "\$NEW_WG_CONFIG" \\
                | sed "s|# PrivateKey = <CONNECTOR_FILLS_THIS_IN>|PrivateKey = \${PRIV_KEY_VALUE}|" \\
                > "\$TMP_CONF"
            chmod 600 "\$TMP_CONF"
            mv -f "\$TMP_CONF" "${WG_CONF}"
            # macOS: wg syncconf targets the utun device, not the
            # logical wg0 alias. wg-quick strip is the same on macOS.
            wg syncconf "\$WG_REAL" <(wg-quick strip "${WG_CONF}") 2>/dev/null || true
            echo "\$REMOTE_CONFIG_VERSION" > "${CONFIG_VERSION_FILE}"
            chmod 600 "${CONFIG_VERSION_FILE}"
        fi
    fi
fi

# Our own overlay /32 for use in same-LAN aliasing below.
OVERLAY_IP=\$(cat "\$OVERLAY_IP_FILE" 2>/dev/null | tr -d '[:space:]')

# add_peer_route: idempotently install a kernel route for one CIDR.
# macOS does not have \`ip route replace\`, so we delete-then-add. The brief
# gap is harmless because heartbeats run every 30s and pings retry.
add_peer_route() {
    local cidr="\$1"
    local iface="\$2"
    local ip="\${cidr%/*}"
    local prefix="\${cidr#*/}"
    [[ -z "\$ip" || -z "\$prefix" ]] && return
    if [[ "\$prefix" == "32" ]]; then
        route -nq delete -host "\$ip" 2>/dev/null
        route -nq add -host "\$ip" -interface "\$iface" 2>/dev/null
    else
        route -nq delete -net "\$cidr" 2>/dev/null
        route -nq add -net "\$cidr" -interface "\$iface" 2>/dev/null
    fi
}

del_peer_route() {
    local cidr="\$1"
    local ip="\${cidr%/*}"
    local prefix="\${cidr#*/}"
    [[ -z "\$ip" || -z "\$prefix" ]] && return
    if [[ "\$prefix" == "32" ]]; then
        route -nq delete -host "\$ip" 2>/dev/null
    else
        route -nq delete -net "\$cidr" 2>/dev/null
    fi
}

# get_phys_default: echoes "<iface> <gateway>" for the non-wg default route.
get_phys_default() {
    route -n get default 2>/dev/null | awk '
        /interface/ { iface = \$2 }
        /gateway/   { gw = \$2 }
        END { if (iface != "" && iface != "'"\$WG_REAL"'") print iface, gw }
    '
}

# ── First pass: extract control-plane signals from peer list ──────────────
WANT_ROUTE_ALL=0
ROUTE_ALL_EP=""
ON_SAME_LAN=0
SAME_LAN_PEER_CIDRS=""
while read -r _p; do
    _a=\$(echo "\$_p" | jq -r '.allowed_ips')
    _sl=\$(echo "\$_p" | jq -r '.on_same_lan // false')
    if [[ "\$_a" == *"0.0.0.0/0"* ]]; then
        WANT_ROUTE_ALL=1
        ROUTE_ALL_EP=\$(echo "\$_p" | jq -r '.endpoint // empty')
    fi
    if [[ "\$_sl" == "true" ]]; then
        ON_SAME_LAN=1
        for _c in \$(echo "\$_a" | tr ',' ' '); do
            SAME_LAN_PEER_CIDRS="\$SAME_LAN_PEER_CIDRS \$_c"
        done
    fi
done < <(echo "\$RESPONSE" | jq -c '.peers[]' 2>/dev/null)

# ── Route-all (full VPN) state machine ──────────────────────────────────────
ROUTE_ALL_PREV=\$(cat "\$ROUTE_ALL_STATE" 2>/dev/null || echo "off")

if [[ "\$WANT_ROUTE_ALL" = "1" && "\$ON_SAME_LAN" = "0" && -n "\$ROUTE_ALL_EP" ]]; then
    # Install exception route for the host's public endpoint via the
    # current default gateway (physical link), then overlay the tunnel
    # with two /1 routes — more specific than /0 so the exception wins.
    # We skip route-all when on_same_lan is set: the tunnel can't be
    # trusted when we're on the host's LAN (hairpin NAT would break the
    # handshake) and the LAN already carries the traffic we care about.
    ENDPOINT_IP="\${ROUTE_ALL_EP%:*}"
    read -r _ DEFAULT_GW < <(get_phys_default)
    if [[ -n "\$DEFAULT_GW" && -n "\$ENDPOINT_IP" ]]; then
        route -nq delete -host "\$ENDPOINT_IP" 2>/dev/null
        route -nq add -host "\$ENDPOINT_IP" "\$DEFAULT_GW" 2>/dev/null
    fi
    route -nq delete -net 0.0.0.0/1   2>/dev/null
    route -nq add    -net 0.0.0.0/1   -interface "\$WG_REAL" 2>/dev/null
    route -nq delete -net 128.0.0.0/1 2>/dev/null
    route -nq add    -net 128.0.0.0/1 -interface "\$WG_REAL" 2>/dev/null
    echo "on|\${ENDPOINT_IP}" > "\$ROUTE_ALL_STATE"
elif [[ "\$ROUTE_ALL_PREV" == on* ]]; then
    # Transition OUT: tear down /1 routes + endpoint exception
    route -nq delete -net 0.0.0.0/1   2>/dev/null
    route -nq delete -net 128.0.0.0/1 2>/dev/null
    PREV_EP="\${ROUTE_ALL_PREV#*|}"
    [[ -n "\$PREV_EP" ]] && route -nq delete -host "\$PREV_EP" 2>/dev/null
    echo "off" > "\$ROUTE_ALL_STATE"
fi

# ── Same-LAN state machine ─────────────────────────────────────────────────
# State format: "on|<iface>|<overlay-ip>" when aliased, "off" otherwise.
SAME_LAN_PREV=\$(cat "\$SAME_LAN_STATE" 2>/dev/null || echo "off")

if [[ "\$ON_SAME_LAN" = "1" && -n "\$OVERLAY_IP" ]]; then
    read -r PHYS_IFACE _ < <(get_phys_default)
    if [[ -n "\$PHYS_IFACE" && "\$SAME_LAN_PREV" != on* ]]; then
        # Transition IN: alias overlay IP on the physical interface so
        # LAN devices can ARP-resolve us at the overlay address.
        # macOS uses "ifconfig <iface> alias <ip> <mask>".
        ifconfig "\$PHYS_IFACE" alias "\$OVERLAY_IP" 255.255.255.255 2>/dev/null || true
        echo "on|\${PHYS_IFACE}|\${OVERLAY_IP}" > "\$SAME_LAN_STATE"
    fi
    # Remove any stale tunnel routes we previously installed for the
    # same-LAN peer's allowed_ips — physical LAN routing handles them.
    for _c in \$SAME_LAN_PEER_CIDRS; do
        del_peer_route "\$_c"
    done
elif [[ "\$SAME_LAN_PREV" == on* ]]; then
    # Transition OUT: remove alias. Per-peer loop below will reinstall
    # normal tunnel routes for the host on the next heartbeat.
    IFS='|' read -r _ PREV_IFACE PREV_OVERLAY <<< "\$SAME_LAN_PREV"
    if [[ -n "\$PREV_IFACE" && -n "\$PREV_OVERLAY" ]]; then
        ifconfig "\$PREV_IFACE" -alias "\$PREV_OVERLAY" 2>/dev/null || true
    fi
    echo "off" > "\$SAME_LAN_STATE"
fi

# ── BYO Exit: upstream WireGuard tunnel state machine (host nodes) ─────────
# The heartbeat response carries an optional \`upstream_exit\` object for host
# nodes. Brain ships the full wg_config inline; we persist it as
# /etc/wireguard/wg0-up.conf and \`wg-quick up\` it.
#
# macOS reachability model (tested setup: Mullvad + Sonoma/Sequoia behind
# consumer NAT): there's no \`ip rule fwmark\` or iptables equivalent, so
# when wg-quick takes over the default route, the host's own wg0 listener
# ends up sending its keepalives and handshake replies out through the
# upstream tunnel. The upstream provider's NAT allocates an outbound
# mapping, the discover sidecar observes the host's new post-NAT source
# address, and the brain pushes that Mullvad-mapped endpoint to every
# peer on the next heartbeat. PersistentKeepalive=25 on every peer keeps
# the mapping open, so inbound peer traffic reaches the host without any
# router port forwarding. This is the intended path on macOS and is
# verified in our tested setup — it assumes the upstream provider's NAT
# is friendly to UDP source-port preservation (Mullvad is). See
# docs/BYO_EXIT.md "Host-reachability policy routing" for the full flow.
UPSTREAM_STATE_FILE="${KEY_DIR}/upstream_exit_state"
UPSTREAM_CONF="/etc/wireguard/wg0-up.conf"

WANT_UPSTREAM_ID=\$(echo "\$RESPONSE" | jq -r '.upstream_exit.id // empty' 2>/dev/null)
WANT_UPSTREAM_CFG=\$(echo "\$RESPONSE" | jq -r '.upstream_exit.wg_config // empty' 2>/dev/null)
PREV_UPSTREAM_ID=\$(cat "\$UPSTREAM_STATE_FILE" 2>/dev/null || echo "off")

install_upstream_tunnel() {
    local cfg="\$1"
    umask 077
    # wg-quick on macOS insists on the .conf being the last path component
    # name, so we write it once and bring up by file path.
    echo "\$cfg" > "\$UPSTREAM_CONF"
    # wg-quick up handles interface creation + default-route takeover
    wg-quick up "\$UPSTREAM_CONF" 2>/dev/null || true
}

teardown_upstream_tunnel() {
    wg-quick down "\$UPSTREAM_CONF" 2>/dev/null || true
    # Clean up stale wireguard-go socket if the interface went away weirdly
    rm -f /var/run/wireguard/wg0-up.* 2>/dev/null || true
    rm -f "\$UPSTREAM_CONF"
}

if [[ -n "\$WANT_UPSTREAM_ID" && -n "\$WANT_UPSTREAM_CFG" ]]; then
    if [[ "\$PREV_UPSTREAM_ID" != "\$WANT_UPSTREAM_ID" ]]; then
        [[ "\$PREV_UPSTREAM_ID" != "off" ]] && teardown_upstream_tunnel
        install_upstream_tunnel "\$WANT_UPSTREAM_CFG"
        echo "\$WANT_UPSTREAM_ID" > "\$UPSTREAM_STATE_FILE"
    fi
elif [[ "\$PREV_UPSTREAM_ID" != "off" ]]; then
    teardown_upstream_tunnel
    echo "off" > "\$UPSTREAM_STATE_FILE"
fi

# ── Apply peer map updates + stale route cleanup ──────────────────────────
# wg set updates WireGuard state but does NOT add kernel routes. Install a
# route for each allowed_ips CIDR so packets actually reach the tunnel.
# 0.0.0.0/0 handled above via split-tunnel; peers flagged on_same_lan skip
# route installation entirely (LAN routing handles them).
#
# Stale route cleanup: track installed routes in a state file. On each
# heartbeat, diff old vs new and remove routes no longer in the peer list.
# This handles profile route policy changes (split→off, CIDR removal).

INSTALLED_ROUTES_FILE="${KEY_DIR}/installed_routes"
PREV_ROUTES=""
[[ -f "\$INSTALLED_ROUTES_FILE" ]] && PREV_ROUTES=\$(cat "\$INSTALLED_ROUTES_FILE")
: > "\${INSTALLED_ROUTES_FILE}.new"

echo "\$RESPONSE" | jq -c '.peers[]' 2>/dev/null | while read -r peer; do
    PUBKEY=\$(echo "\$peer" | jq -r '.public_key')
    ALLOWED=\$(echo "\$peer" | jq -r '.allowed_ips')
    EP=\$(echo "\$peer" | jq -r '.endpoint // empty')
    PEER_SAME_LAN=\$(echo "\$peer" | jq -r '.on_same_lan // false')
    if [[ -n "\$EP" ]]; then
        wg set "\$WG_REAL" peer "\$PUBKEY" allowed-ips "\$ALLOWED" endpoint "\$EP" persistent-keepalive 25
    else
        wg set "\$WG_REAL" peer "\$PUBKEY" allowed-ips "\$ALLOWED" persistent-keepalive 25
    fi
    [[ "\$PEER_SAME_LAN" == "true" ]] && continue
    echo "\$ALLOWED" | tr ',' '\\n' | tr -d ' ' | while read -r cidr; do
        [[ -z "\$cidr" || "\$cidr" == "0.0.0.0/0" ]] && continue
        add_peer_route "\$cidr" "\$WG_REAL"
        echo "\$cidr" >> "\${INSTALLED_ROUTES_FILE}.new"
    done
done

# Remove stale routes: CIDRs in the old set but not in the new set.
if [[ -s "\${INSTALLED_ROUTES_FILE}.new" ]]; then
    sort -u "\${INSTALLED_ROUTES_FILE}.new" > "\${INSTALLED_ROUTES_FILE}.sorted" 2>/dev/null || true
    if [[ -n "\$PREV_ROUTES" ]]; then
        echo "\$PREV_ROUTES" | while read -r old_cidr; do
            [[ -z "\$old_cidr" ]] && continue
            if ! grep -qxF "\$old_cidr" "\${INSTALLED_ROUTES_FILE}.sorted" 2>/dev/null; then
                del_peer_route "\$old_cidr"
            fi
        done
    fi
    mv -f "\${INSTALLED_ROUTES_FILE}.sorted" "\$INSTALLED_ROUTES_FILE" 2>/dev/null || true
    rm -f "\${INSTALLED_ROUTES_FILE}.new" 2>/dev/null || true
else
    # No routes installed this cycle — remove all previously tracked.
    if [[ -n "\$PREV_ROUTES" ]]; then
        echo "\$PREV_ROUTES" | while read -r old_cidr; do
            [[ -z "\$old_cidr" ]] && continue
            del_peer_route "\$old_cidr"
        done
    fi
    rm -f "\$INSTALLED_ROUTES_FILE" "\${INSTALLED_ROUTES_FILE}.new" 2>/dev/null || true
fi

# ── Remove stale WireGuard peers ──────────────────────────────────────────
# If the brain stopped advertising a peer (e.g., native-LAN host-routed
# mode), remove it from WireGuard's crypto-key routing table.
RESPONSE_PUBKEYS=\$(echo "\$RESPONSE" | jq -r '.peers[].public_key' 2>/dev/null | sort -u)
WG_PUBKEYS=\$(wg show "\$WG_REAL" peers 2>/dev/null | sort -u)
if [[ -n "\$WG_PUBKEYS" ]]; then
    echo "\$WG_PUBKEYS" | while read -r wg_pk; do
        [[ -z "\$wg_pk" ]] && continue
        if ! echo "\$RESPONSE_PUBKEYS" | grep -qxF "\$wg_pk"; then
            wg set "\$WG_REAL" peer "\$wg_pk" remove 2>/dev/null || true
        fi
    done
fi
HBSCRIPT
    chmod +x "$HEARTBEAT_SCRIPT"
}

# ── Subcommand dispatch ───────────────────────────────────────────────────────
SUBCMD="${1:-}"

if [[ "$SUBCMD" != "enroll" && "$SUBCMD" != "unenroll" && "$SUBCMD" != "update" && "$SUBCMD" != "rotate-secret" ]]; then
    echo "Usage:"
    echo "  $0 enroll       <TOKEN> <BRAIN_URL> [NODE_NAME] [ROLE]"
    echo "  $0 update       <NEW_BRAIN_URL>"
    echo "  $0 unenroll     [BRAIN_URL]"
    echo "  $0 rotate-secret [BRAIN_URL]"
    exit 1
fi

shift  # consume subcommand

if [[ "$SUBCMD" == "unenroll" ]]; then
    BRAIN_URL="${1:-}"
    # If no brain URL given, try to read it from stored file
    if [[ -z "$BRAIN_URL" ]]; then
        for d in /etc/wireguard/wg0 /etc/wireguard/abslink; do
            [[ -f "$d/brain_url" ]] && BRAIN_URL=$(cat "$d/brain_url") && break
        done
    fi
    [[ -n "$BRAIN_URL" ]] || { echo "Usage: $0 unenroll [BRAIN_URL]"; echo "(Could not auto-detect brain URL — provide it explicitly)"; exit 1; }
elif [[ "$SUBCMD" == "update" ]]; then
    BRAIN_URL="${1:-}"
    [[ -n "$BRAIN_URL" ]] || { echo "Usage: $0 update <NEW_BRAIN_URL>"; exit 1; }
elif [[ "$SUBCMD" == "rotate-secret" ]]; then
    BRAIN_URL="${1:-}"
    if [[ -z "$BRAIN_URL" ]]; then
        for d in /etc/wireguard/wg0 /etc/wireguard/abslink; do
            [[ -f "$d/brain_url" ]] && BRAIN_URL=$(cat "$d/brain_url") && break
        done
    fi
    [[ -n "$BRAIN_URL" ]] || { echo "Usage: $0 rotate-secret [BRAIN_URL]"; exit 1; }
else
    TOKEN="${1:-}"
    BRAIN_URL="${2:-}"
    NODE_NAME="${3:-$(hostname -s)}"
    ROLE="${4:-client}"
    [[ -n "$TOKEN" && -n "$BRAIN_URL" ]] || {
        echo "Usage: $0 enroll <TOKEN> <BRAIN_URL> [NODE_NAME] [ROLE]"
        exit 1
    }
fi

BRAIN_URL="${BRAIN_URL%/}"

# ── ROTATE-SECRET ─────────────────────────────────────────────────────────────
if [[ "$SUBCMD" == "rotate-secret" ]]; then
    [[ -f "$NODE_ID_FILE" ]] || die "No node_id found. This system does not appear to be enrolled."
    NODE_ID=$(cat "$NODE_ID_FILE")
    log "Rotating device secret for node ${NODE_ID} at ${BRAIN_URL}"

    CUR_SECRET=$(cat "$DEVICE_SECRET_FILE" 2>/dev/null || true)
    ROTATE_ARGS=( -sf -X POST -H "Content-Type: application/json" )
    [[ -n "$CUR_SECRET" ]] && ROTATE_ARGS+=( -H "X-Device-Secret: $CUR_SECRET" )
    RESP=$(curl "${ROTATE_ARGS[@]}" "${BRAIN_URL}/api/v1/nodes/${NODE_ID}/rotate-secret" -d '{}') \
        || die "rotate-secret request failed — brain unreachable or current secret rejected."

    NEW_SECRET=$(echo "$RESP" | jq -r '.device_secret // empty')
    [[ -n "$NEW_SECRET" ]] || die "Brain returned no device_secret in rotate response: $RESP"

    TMP_SECRET=$(mktemp "$KEY_DIR/.device_secret.XXXXXX")
    printf '%s' "$NEW_SECRET" > "$TMP_SECRET"
    chmod 600 "$TMP_SECRET"
    mv -f "$TMP_SECRET" "$DEVICE_SECRET_FILE"

    log "Device secret rotated successfully. Future heartbeats will use the new secret."
    exit 0
fi

# ── UPDATE ────────────────────────────────────────────────────────────────────
if [[ "$SUBCMD" == "update" ]]; then
    log "wg0 update — migrating to brain at ${BRAIN_URL}"

    # ── 1. Detect current key dir (legacy or new) ────────────────────────────
    OLD_KEY_DIR=""
    if [[ -d /etc/wireguard/abslink ]]; then
        OLD_KEY_DIR="/etc/wireguard/abslink"
    fi

    if [[ -n "$OLD_KEY_DIR" && "$OLD_KEY_DIR" != "$KEY_DIR" ]]; then
        log "Migrating key directory: ${OLD_KEY_DIR} → ${KEY_DIR}"
        mv "$OLD_KEY_DIR" "$KEY_DIR"
    fi

    NODE_ID_FILE="${KEY_DIR}/node_id"
    [[ -f "$NODE_ID_FILE" ]] || die "No node_id found. This system does not appear to be enrolled."
    NODE_ID=$(cat "$NODE_ID_FILE")
    log "Node ID: ${NODE_ID}"

    # ── 2. Store brain URL for future reference ──────────────────────────────
    echo "$BRAIN_URL" > "${KEY_DIR}/brain_url"
    chmod 600 "${KEY_DIR}/brain_url"

    # ── 3. Migrate legacy heartbeat script name ──────────────────────────────
    OLD_HB="/usr/local/bin/abslink-heartbeat"
    if [[ -f "$OLD_HB" && "$OLD_HB" != "$HEARTBEAT_SCRIPT" ]]; then
        log "Renaming heartbeat script: abslink-heartbeat → $(basename $HEARTBEAT_SCRIPT)"
        mv "$OLD_HB" "$HEARTBEAT_SCRIPT"
    fi

    # ── 4. Rewrite heartbeat script from current template ────────────────────
    # We don't sed-patch — too fragile. Just regenerate the whole script with
    # the latest brain URL, route logic, TX/RX reporting, etc.
    write_heartbeat_script
    log "Rewrote heartbeat script with latest template (brain=${BRAIN_URL})"

    # ── 5. Migrate legacy launchd plists ─────────────────────────────────────
    OLD_HB_PLIST="/Library/LaunchDaemons/com.abslink.heartbeat.plist"
    OLD_WG_PLIST="/Library/LaunchDaemons/com.abslink.wireguard.plist"

    if [[ -f "$OLD_HB_PLIST" ]]; then
        log "Migrating heartbeat launchd plist: com.abslink → io.wg0"
        launchctl unload "$OLD_HB_PLIST" 2>/dev/null || true
        # Rewrite with new label and new heartbeat script path
        sed 's|com\.abslink\.heartbeat|io.wg0.heartbeat|g; s|abslink-heartbeat|wg0-heartbeat|g' \
            "$OLD_HB_PLIST" > "$LAUNCHDAEMON_PLIST"
        rm -f "$OLD_HB_PLIST"
        launchctl load "$LAUNCHDAEMON_PLIST"
        log "Heartbeat daemon reloaded as io.wg0.heartbeat"
    elif [[ -f "$LAUNCHDAEMON_PLIST" ]]; then
        # Just reload with the new heartbeat script path in case it was updated
        launchctl unload "$LAUNCHDAEMON_PLIST" 2>/dev/null || true
        launchctl load "$LAUNCHDAEMON_PLIST"
        log "Heartbeat daemon reloaded"
    fi

    if [[ -f "$OLD_WG_PLIST" ]]; then
        log "Migrating WireGuard watchdog plist: com.abslink → io.wg0"
        launchctl unload "$OLD_WG_PLIST" 2>/dev/null || true
        sed 's|com\.abslink\.wireguard|io.wg0.wireguard|g; s|abslink-|wg0-|g' \
            "$OLD_WG_PLIST" > "$WG_WATCHDOG_PLIST"
        rm -f "$OLD_WG_PLIST"
        launchctl load "$WG_WATCHDOG_PLIST"
        log "WireGuard watchdog reloaded as io.wg0.wireguard"
    fi

    # ── 6. Migrate legacy postup/predown scripts ────────────────────────────
    for pair in "abslink-postup:wg0-postup" "abslink-predown:wg0-predown"; do
        old="/usr/local/bin/${pair%%:*}"
        new="/usr/local/bin/${pair##*:}"
        if [[ -f "$old" && "$old" != "$new" ]]; then
            mv "$old" "$new"
        fi
    done
    # Update PostUp/PreDown references in WireGuard config
    if [[ -f "$WG_CONF" ]]; then
        sed -i '' 's|abslink-postup|wg0-postup|g; s|abslink-predown|wg0-predown|g' "$WG_CONF"
    fi

    # ── 7. Install/update wg0 CLI ────────────────────────────────────────────
    if curl -fsSL "${BRAIN_URL%/api*}/wg0-status.sh" -o /usr/local/bin/wg0 2>/dev/null \
       || curl -fsSL "https://wg0.io/wg0-status.sh" -o /usr/local/bin/wg0 2>/dev/null; then
        chmod +x /usr/local/bin/wg0
        log "Updated wg0 CLI tool"
    fi
    # Remove old abslink CLI if present
    rm -f /usr/local/bin/abslink 2>/dev/null || true

    # ── 8. Force an immediate heartbeat to verify ────────────────────────────
    log "Running heartbeat to verify connectivity..."
    if bash "$HEARTBEAT_SCRIPT" 2>/dev/null; then
        log "Heartbeat succeeded — connected to ${BRAIN_URL}"
    else
        warn "Heartbeat failed — check that ${BRAIN_URL} is reachable"
    fi

    log ""
    log "Update complete."
    log "  Brain URL:  ${BRAIN_URL}"
    log "  Node ID:    ${NODE_ID}"
    log "  Key dir:    ${KEY_DIR}"
    log ""
    log "Run 'wg0 status' to verify tunnel health."
    exit 0
fi

# ── UNENROLL ──────────────────────────────────────────────────────────────────
if [[ "$SUBCMD" == "unenroll" ]]; then
    log "Starting unenroll from Brain at ${BRAIN_URL} ..."

    if [[ ! -f "$NODE_ID_FILE" ]]; then
        die "No node_id found at ${NODE_ID_FILE}. This system does not appear to be enrolled."
    fi
    NODE_ID=$(cat "$NODE_ID_FILE")
    log "Node ID: ${NODE_ID}"

    log "Notifying Brain to remove node..."
    DEVICE_SECRET=$(cat "$DEVICE_SECRET_FILE" 2>/dev/null || true)
    UNENROLL_ARGS=( -sf -X DELETE )
    [[ -n "$DEVICE_SECRET" ]] && UNENROLL_ARGS+=( -H "X-Device-Secret: $DEVICE_SECRET" )
    if curl "${UNENROLL_ARGS[@]}" "${BRAIN_URL}/api/v1/nodes/${NODE_ID}/self" >/dev/null 2>&1; then
        log "Brain confirmed node removal."
    else
        warn "Brain request failed (unreachable?). Continuing local cleanup."
    fi

    log "Bringing down WireGuard interface ${WG_IFACE}..."
    if [[ -f "$WG_CONF" ]]; then
        wg-quick down "$WG_CONF" 2>/dev/null || true
    fi
    # wg-quick down can fail if the conf was already removed or the interface
    # was left orphaned by a previous failed enroll. Force-remove the utun too.
    UTUN=$(wg show "$WG_IFACE" 2>/dev/null | awk '/^interface:/{print $2}' || true)
    if [[ -z "$UTUN" ]]; then
        # Fallback: find the utun holding our WireGuard socket
        UTUN=$(ifconfig -l | tr ' ' '\n' | grep '^utun' | while read iface; do
            wg show "$iface" 2>/dev/null | grep -q 'listen port' && echo "$iface" && break
        done || true)
    fi
    [[ -n "$UTUN" ]] && ifconfig "$UTUN" destroy 2>/dev/null || true

    if [[ -f "$WG_WATCHDOG_PLIST" ]]; then
        log "Removing launchd WireGuard watchdog daemon..."
        launchctl unload "$WG_WATCHDOG_PLIST" 2>/dev/null || true
        rm -f "$WG_WATCHDOG_PLIST"
    fi

    if [[ -f "$LAUNCHDAEMON_PLIST" ]]; then
        log "Removing launchd heartbeat daemon..."
        launchctl unload "$LAUNCHDAEMON_PLIST" 2>/dev/null || true
        rm -f "$LAUNCHDAEMON_PLIST"
    fi

    # Flush NAT rules added by native host mode
    if [[ -f "$PREDOWN_SCRIPT" ]]; then
        bash "$PREDOWN_SCRIPT" 2>/dev/null || true
    fi

    rm -f "$HEARTBEAT_SCRIPT" "$POSTUP_SCRIPT" "$PREDOWN_SCRIPT"
    rm -f /var/run/wireguard/${WG_IFACE}.sock 2>/dev/null || true
    rm -f "$WG_CONF"
    rm -rf "$KEY_DIR"
    log "Unenroll complete. This node has been removed from wg0."
    exit 0
fi

# ── ENROLL ────────────────────────────────────────────────────────────────────
log "wg0 macOS Connector — arch=${ARCH}, Homebrew=${BREW_PREFIX}"

# ── Homebrew check ────────────────────────────────────────────────────────────
if [[ ! -x "$BREW" ]]; then
    log "Homebrew not found at ${BREW_PREFIX}. Installing Homebrew..."
    # Run install as the actual user (not root) — Homebrew refuses to run as root
    REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo $USER)}"
    sudo -u "$REAL_USER" /bin/bash -c \
        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
        || die "Homebrew installation failed."
    log "Homebrew installed."
fi

# ── Install missing dependencies ──────────────────────────────────────────────
REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo $USER)}"
for pkg in wireguard-tools jq; do
    if ! sudo -u "$REAL_USER" "$BREW" list "$pkg" >/dev/null 2>&1; then
        log "Installing ${pkg} via Homebrew..."
        sudo -u "$REAL_USER" "$BREW" install "$pkg" \
            || die "Failed to install ${pkg}. Run 'brew install ${pkg}' manually."
    fi
done

# Add Homebrew bin to PATH for wg / wg-quick
export PATH="${BREW_PREFIX}/bin:${BREW_PREFIX}/sbin:$PATH"

# ── Dependency check ──────────────────────────────────────────────────────────
for cmd in wg wg-quick curl jq; do
    command -v "$cmd" >/dev/null 2>&1 || die "Required command '${cmd}' not found after install attempt."
done

# ── Directory setup ───────────────────────────────────────────────────────────
mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"

# ── Key generation ────────────────────────────────────────────────────────────
if [[ ! -f "$PRIV_KEY_FILE" ]]; then
    log "Generating WireGuard keypair..."
    wg genkey | tee "$PRIV_KEY_FILE" | wg pubkey > "$PUB_KEY_FILE"
    chmod 600 "$PRIV_KEY_FILE"
fi
PRIV_KEY=$(cat "$PRIV_KEY_FILE")
PUB_KEY=$(cat "$PUB_KEY_FILE")
log "Public key: ${PUB_KEY}"

# ── Detect public endpoint ────────────────────────────────────────────────────
PUBLIC_IP=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "")
ENDPOINT=""
[[ -n "$PUBLIC_IP" ]] && ENDPOINT="${PUBLIC_IP}:51820"

# ── Enrollment ────────────────────────────────────────────────────────────────
if [[ ! -f "$NODE_ID_FILE" ]]; then
    log "Enrolling node '${NODE_NAME}' (role=${ROLE}, os_type=macos) with Brain at ${BRAIN_URL} ..."

    PAYLOAD=$(cat <<EOF
{
    "token": "${TOKEN}",
    "public_key": "${PUB_KEY}",
    "node_name": "${NODE_NAME}",
    "os_type": "macos",
    "role": "${ROLE}",
    "advertised_routes": [],
    "endpoint": "${ENDPOINT}"
}
EOF
)

    ENROLL_RESPONSE=$(curl -sf -X POST \
        -H "Content-Type: application/json" \
        -d "$PAYLOAD" \
        "${BRAIN_URL}/api/v1/enroll/register") \
        || die "Enrollment failed. Check TOKEN and BRAIN_URL."

    NODE_ID=$(echo "$ENROLL_RESPONSE" | jq -r '.node_id')
    OVERLAY_IP=$(echo "$ENROLL_RESPONSE" | jq -r '.overlay_ip')
    WG_CONFIG=$(echo "$ENROLL_RESPONSE" | jq -r '.wg_config')
    NETWORK_TYPE=$(echo "$ENROLL_RESPONSE" | jq -r '.network_type // "overlay"')
    # Device protocol v2 secret. Empty when brain is still v1-only.
    DEVICE_SECRET=$(echo "$ENROLL_RESPONSE" | jq -r '.device_secret // empty')

    echo "$NODE_ID" > "$NODE_ID_FILE"
    chmod 600 "$NODE_ID_FILE"
    echo "$BRAIN_URL" > "${KEY_DIR}/brain_url"
    chmod 600 "${KEY_DIR}/brain_url"
    if [[ -n "$DEVICE_SECRET" ]]; then
        printf '%s' "$DEVICE_SECRET" > "$DEVICE_SECRET_FILE"
        chmod 600 "$DEVICE_SECRET_FILE"
    fi
    # Bare overlay IP (no /prefix) — used by the heartbeat's same-LAN
    # state machine to alias the overlay /32 on the physical interface.
    echo "${OVERLAY_IP%/*}" > "${KEY_DIR}/overlay_ip"
    chmod 600 "${KEY_DIR}/overlay_ip"

    # ── macOS config post-processing ─────────────────────────────────────────
    #
    # 1. Strip Linux-specific PostUp/PreDown lines (reference /proc or `ip route`).
    #    These will cause wg-quick to fail on macOS.
    #
    # 2. For host role: the brain generates Address = x.x.x.x/NN (gateway subnet prefix).
    #    On macOS, that competing /24 route conflicts with the physical Ethernet interface
    #    already on the same subnet. We rewrite to /32 so only a host route is added,
    #    then enable IP forwarding via a macOS-safe PostUp.
    #
    # 3. For client role: Address is already /32 from the brain — no change needed.

    # Strip Linux PostUp/PreDown
    PROCESSED_CONFIG=$(echo "$WG_CONFIG" | grep -v '^PostUp' | grep -v '^PreDown')

    if [[ "$ROLE" == "host" && "$NETWORK_TYPE" == "native" ]]; then
        log "Native host mode: rewriting Address to /32 and adding macOS IP forwarding + NAT PostUp."

        # Extract the gateway subnet from the original Address line BEFORE rewriting to /32.
        # e.g. "Address = 192.168.1.2/24"  →  GW_SUBNET="192.168.1.0/24"
        ORIG_ADDR=$(echo "$PROCESSED_CONFIG" | awk '/^Address[[:space:]]*=/{print $3}')
        GW_SUBNET=$(python3 -c "import ipaddress; print(str(ipaddress.IPv4Network('${ORIG_ADDR}', strict=False)))" 2>/dev/null || echo "")
        [[ -z "$GW_SUBNET" ]] && die "Could not determine gateway subnet from Address '${ORIG_ADDR}'."
        log "Gateway subnet: ${GW_SUBNET}"

        # Rewrite /NN → /32 on the Address line (avoids competing route with physical LAN)
        PROCESSED_CONFIG=$(echo "$PROCESSED_CONFIG" | \
            sed 's/^\(Address = [0-9][0-9.]*\)\/[0-9]*/\1\/32/')

        # Write PostUp script: IP forwarding + pfctl NAT so LAN devices can reply to tunnel clients.
        # net.inet.proxyarp does not exist on modern macOS; NAT is the reliable alternative.
        cat > "$POSTUP_SCRIPT" << POSTUPEOF
#!/bin/bash
sysctl -w net.inet.ip.forwarding=1
PHYS=\$(route get default | awk '/interface:/{print \$2}')
printf "nat on %s from ${GW_SUBNET} to any -> (%s)\npass all\n" "\$PHYS" "\$PHYS" | pfctl -f - -e 2>/dev/null || true
POSTUPEOF
        chmod +x "$POSTUP_SCRIPT"

        # Write PreDown script: remove NAT rules when interface goes down.
        cat > "$PREDOWN_SCRIPT" << PREDOWNEOF
#!/bin/bash
pfctl -F nat 2>/dev/null || true
PREDOWNEOF
        chmod +x "$PREDOWN_SCRIPT"

        # Insert PostUp/PreDown references into the config after ListenPort line
        PROCESSED_CONFIG=$(echo "$PROCESSED_CONFIG" | \
            awk -v postup="$POSTUP_SCRIPT" -v predown="$PREDOWN_SCRIPT" \
            '/^ListenPort/{print; print "PostUp = " postup; print "PreDown = " predown; next}1')
    fi

    # Substitute private key placeholder
    PROCESSED_CONFIG=$(echo "$PROCESSED_CONFIG" | \
        sed "s|# PrivateKey = <CONNECTOR_FILLS_THIS_IN>|PrivateKey = ${PRIV_KEY}|")

    # Write config
    mkdir -p "$(dirname "$WG_CONF")"
    echo "$PROCESSED_CONFIG" > "$WG_CONF"
    chmod 600 "$WG_CONF"

    log "Enrolled! Assigned IP: ${OVERLAY_IP} | Node ID: ${NODE_ID} | Network type: ${NETWORK_TYPE}"
fi

NODE_ID=$(cat "$NODE_ID_FILE")

# ── Bring up WireGuard ────────────────────────────────────────────────────────
if ! wg show "$WG_IFACE" >/dev/null 2>&1; then
    # Clean up stale socket if wireguard-go died without proper teardown.
    # Without this, wg-quick up fails with "'wg0' already exists".
    rm -f "/var/run/wireguard/${WG_IFACE}.sock" 2>/dev/null || true
    log "Bringing up WireGuard interface ${WG_IFACE}..."
    wg-quick up "$WG_CONF" || die "Failed to bring up WireGuard. Check /var/log/system.log."
fi
log "Interface ${WG_IFACE} is up."

# ── Heartbeat script ──────────────────────────────────────────────────────────
write_heartbeat_script

# ── Install heartbeat — launchd daemon ───────────────────────────────────────
log "Installing launchd heartbeat daemon (every ${HEARTBEAT_INTERVAL}s)..."

# Unload previous version if present
if [[ -f "$LAUNCHDAEMON_PLIST" ]]; then
    launchctl unload "$LAUNCHDAEMON_PLIST" 2>/dev/null || true
fi

cat > "$LAUNCHDAEMON_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.wg0.heartbeat</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${HEARTBEAT_SCRIPT}</string>
    </array>
    <key>StartInterval</key>
    <integer>${HEARTBEAT_INTERVAL}</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/var/log/wg0-heartbeat.log</string>
    <key>StandardOutPath</key>
    <string>/var/log/wg0-heartbeat.log</string>
</dict>
</plist>
PLIST

if launchctl load "$LAUNCHDAEMON_PLIST" 2>/dev/null; then
    log "Heartbeat daemon installed (launchd, every ${HEARTBEAT_INTERVAL}s)."
    log "  Logs: /var/log/wg0-heartbeat.log"
    log "  Status: launchctl list | grep wg0"
else
    warn "launchctl load failed — falling back to background loop."
    while true; do
        sleep "$HEARTBEAT_INTERVAL"
        "$HEARTBEAT_SCRIPT" &>/dev/null || true
    done &
    disown
    log "Heartbeat loop started (PID $!)."
fi

# ── Install WireGuard watchdog — launchd daemon ───────────────────────────────
# wireguard-go exits on crash/reboot. This watchdog polls every 60s and brings
# the interface back up if it's gone, including cleaning any stale socket.
log "Installing launchd WireGuard watchdog daemon..."

if [[ -f "$WG_WATCHDOG_PLIST" ]]; then
    launchctl unload "$WG_WATCHDOG_PLIST" 2>/dev/null || true
fi

cat > "$WG_WATCHDOG_PLIST" <<WGPLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.wg0.wireguard</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>export PATH="${BREW_PREFIX}/bin:${BREW_PREFIX}/sbin:/usr/bin:/bin:/usr/sbin:/sbin"; WG_REAL=\$(cat /var/run/wireguard/${WG_IFACE}.name 2>/dev/null | tr -d '[:space:]'); { [[ -n "\$WG_REAL" ]] &amp;&amp; wg show "\$WG_REAL" &gt;/dev/null 2&gt;&amp;1; } || { rm -f /var/run/wireguard/${WG_IFACE}.sock /var/run/wireguard/${WG_IFACE}.name; wg-quick up ${WG_CONF}; }</string>
    </array>
    <key>StartInterval</key>
    <integer>60</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/var/log/wg0-wireguard.log</string>
    <key>StandardOutPath</key>
    <string>/var/log/wg0-wireguard.log</string>
</dict>
</plist>
WGPLIST

if launchctl load "$WG_WATCHDOG_PLIST" 2>/dev/null; then
    log "WireGuard watchdog installed (launchd, checks every 60s, auto-restarts on crash/reboot)."
    log "  Logs: /var/log/wg0-wireguard.log"
else
    warn "WireGuard watchdog launchctl load failed — WireGuard will not auto-restart."
fi

# ── Install wg0 status CLI ────────────────────────────────────────────────────
REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo $USER)}"
if curl -fsSL "https://wg0.io/wg0-status.sh" -o /usr/local/bin/wg0 2>/dev/null; then
    chmod +x /usr/local/bin/wg0
    log "Installed: 'wg0 status' command"
fi

log ""
log "wg0 connector setup complete."
log "  WireGuard interface: ${WG_IFACE}"
log "  Node ID:             ${NODE_ID}"
log "  Config:              ${WG_CONF}"
log "  Keys:                ${KEY_DIR}/"
log ""
log "Check tunnel status anytime: wg0 status"
log ""
log "To unenroll this node later:"
log "  sudo $0 unenroll ${BRAIN_URL}"
